### PR TITLE
fix(download): work around `hyper` hang issue by adjusting `reqwest` config

### LINKED ISSUE #3852: Tests relying on `reqwest::Client` may fail with "dispatch task is gone: runtime dropped the dispatch task"
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

This is causing irregular failures for different CI platforms:
- Linux
  - https://github.com/rust-lang/rustup/actions/runs/9303236385/job/25605096671
  - https://github.com/rust-lang/rustup/actions/runs/9354772182/job/25748366479
  - https://github.com/rust-lang/rustup/actions/runs/9337787790/job/25700115067
  - https://github.com/rust-lang/rustup/actions/runs/9343224087/job/25712479916
- Windows
  - https://github.com/rust-lang/rustup/actions/runs/9335696949/job/25695378538

The error message here is identical (although the exact test that failed might differ):
```console
running 395 tests
...
test suite::cli_exact::check_updates_with_update ... FAILED
error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateD58GcC/release-stable.toml': failed to make network request: error sending request for url (https://static.rust-lang.org/rustup/release-stable.toml): client error (SendRequest): dispatch task is gone: runtime dropped the dispatch task
```

### Notes

Possibly related to https://github.com/hyperium/hyper/issues/2312, https://github.com/Azure/azure-sdk-for-rust/pull/1550 or https://github.com/fussybeaver/bollard/issues/387#issuecomment-2008133973.

I'm pretty sure that #3367 has caused this.

### PR DESCRIPTION
**Pull request by rami3l**
This PR tries to mitigate #3852 by applying https://github.com/Azure/azure-sdk-for-rust/pull/1550 's hack to all the `ClientBuilder`'s I can find across the repo.

The verification of the mitigation is not easy, since `async` execution is not so deterministic. Nevertheless, as this seems to be a widely encountered issue with `hyper` and `reqwest`, I suggest we merge this first and see how it goes.

### CODE REVIEW

File: download/src/lib.rs [hunk 1]
```diff
@@ -345,6 +345,10 @@ pub mod reqwest_be {
 
     fn client_generic() -> ClientBuilder {
         Client::builder()
+            // HACK: set `pool_max_idle_per_host` to `0` to avoid an issue in the underlying
```
Comment (djc) [inline download/src/lib.rs:348]: Can you explain why this is necessary/why there is no better solution for this?

Comment (rami3l) [reply download/src/lib.rs:348]: @djc The underlying issue is https://github.com/hyperium/hyper/issues/2312, see https://github.com/hyperium/hyper/issues/2312#issuecomment-778005053 for the first appearance of this hack. It is suspected that there is a hyper pool deadlock underneath, and this workaround has been used by many to successfully mitigate the issue (see all the external references below).

**Review by djc — APPROVED** [review]

File: download/src/lib.rs (hunk 1 above)
Comment (djc) [reply download/src/lib.rs:348]: Do we have a good reproduction scenario?

Comment (rami3l) [reply download/src/lib.rs:348]: @djc Unfortunately not yet, and that's the tricky part of this thing I guess... If it really is a concurrency bug, then it'll be rather hard to track and to fix (that's also why that issue has been open for such a long time I guess, a previous project that I collaborated on has also hit it back in 2020, and the same hack was applied 🤔).

As far as our CI is concerned, we can see several failures in the past 5 days caused by this one, and they are all "solved" by relaunching the test task. The particular test(s) that failed varied from time to time, but I'm sure that all those tests are `reqwest`-related.

Anyway, this PR intentionally won't close #3852, and I'll keep an eye on https://github.com/hyperium/hyper/issues/2312 as well as our CI in the upcoming weeks.

Comment (rami3l) [reply download/src/lib.rs:348]: @djc The workaround seems to be working: our CI hasn't been failing for this reason in the past 5 days.
