### PR TITLE
Fix install message misalignment

### LINKED ISSUE #4759: installation output could be more column-y
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

1) rustup update
=> the column-like output still looks a bit wonky for longly named components
```
info: syncing channel updates for stable-x86_64-unknown-linux-gnu
info: syncing channel updates for beta-x86_64-unknown-linux-gnu
info: syncing channel updates for nightly-x86_64-unknown-linux-gnu
info: latest update on 2026-03-18 for version 1.96.0-nightly (91021ccc7 2026-03-17)
info: removing previous version of component gcc-x86_64-unknown-linux-gnu
info: removing previous version of component rustc-codegen-gcc
info: removing previous version of component rustfmt
info: removing previous version of component rustc-dev
info: removing previous version of component rustc-codegen-cranelift
info: removing previous version of component rust-src
info: removing previous version of component rust-docs-json
info: removing previous version of component rust-docs
info: removing previous version of component rust-analyzer
info: removing previous version of component rust-analysis
info: removing previous version of component miri
info: removing previous version of component llvm-tools
info: removing previous version of component llvm-bitcode-linker
info: removing previous version of component clippy
info: removing previous version of component cargo
info: removing previous version of component rust-std
info: removing previous version of component rustc
info: downloading 17 components
gcc-x86_64-unknown-linux-gnu installed                       13.68 MiB
rustc-codegen-gcc installed                     1003.07 KiB
      rustfmt installed                        2.06 MiB
    rustc-dev installed                      114.74 MiB
rustc-codegen-cranelift installed                        2.41 MiB
     rust-src installed                        3.68 MiB
rust-docs-json installed                        2.50 MiB
    rust-docs installed                       21.25 MiB
rust-analyzer installed                        9.00 MiB
rust-analysis installed                       15.83 KiB
         miri installed                        3.45 MiB
   llvm-tools installed                       37.41 MiB
llvm-bitcode-linker installed                     1001.30 KiB
       clippy installed                        4.56 MiB
        cargo installed                       10.51 MiB
     rust-std installed                       28.20 MiB
        rustc installed                       76.35 MiB                                                                                                                                                                                                                                                                     info: syncing channel updates for 1.93-x86_64-unknown-linux-gnu

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.94.0 (4a4ef493e 2026-03-02)
    beta-x86_64-unknown-linux-gnu unchanged - rustc 1.95.0-beta.3 (94a8e826a 2026-03-08)
   nightly-x86_64-unknown-linux-gnu updated - rustc 1.96.0-nightly (91021ccc7 2026-03-17) (from rustc 1.96.0-nightly (3645249d7 2026-03-16))
    1.93-x86_64-unknown-linux-gnu unchanged - rustc 1.93.1 (01f6ddf75 2026-02-11)

info: checking for self-update (current version: 1.29.0)
```

maybe the `installed` entries could line up properly?

### Steps

see above

### Possible Solution(s)

_No response_

### Notes

_No response_

### Rustup version

```console
rustup 1.29.0 (28d1352db 2026-03-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: the currently active `rustc` version is `rustc 1.96.0-nightly (91021ccc7 2026-03-17)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/matthias/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (active, default)
nightly-2025-12-19-x86_64-unknown-linux-gnu
nightly-2026-02-17-x86_64-unknown-linux-gnu
nightly-2026-02-22-x86_64-unknown-linux-gnu
nightly-2026-03-05-x86_64-unknown-linux-gnu
1.93-x86_64-unknown-linux-gnu
alt-master
bisector-ci-0c68443b0a0469e4211acca7e7b06e14f256ada8-x86_64-unknown-linux-gnu
bisector-ci-0df64c57843a9612c68dd78bafa133f5b5d340c4-x86_64-unknown-linux-gnu
bisector-ci-141e61d810b48adba1a90ff091a25930cbf3ffc3-x86_64-unknown-linux-gnu
bisector-ci-18d13b5332916ffca8eadb9106d54b5b434e9978-x86_64-unknown-linux-gnu
bisector-ci-1b7d722f429f09c87b08b757d89c689c6cf7f6e7-x86_64-unknown-linux-gnu
bisector-ci-1be6b13be73dc12e98e51b403add4c41a0b77759-x86_64-unknown-linux-gnu
bisector-ci-1ed488274bec5bf5cfe6bf7a1cc089abcc4ebd68-x86_64-unknown-linux-gnu
bisector-ci-20f1c045c46aecba6a6aeda55fe6659b26871c87-x86_64-unknown-linux-gnu
bisector-ci-217cb73577ed6f30a2005dd75bab01d23ec4cd60-x86_64-unknown-linux-gnu
bisector-ci-2819dfdd45dba873a9cedc14a35ec1a38185720a-x86_64-unknown-linux-gnu
bisector-ci-28d0a4a205f9e511ad2f51ee79a4aa19a704a455-x86_64-unknown-linux-gnu
bisector-ci-29d913df6c5346d055217960096c369dfec213e9-x86_64-unknown-linux-gnu
bisector-ci-2cb654d8000806e0739319cfd54210ddc07ffd86-x86_64-unknown-linux-gnu
bisector-ci-305d63ffb5d983fe7316e4ae5f0e57aeba6e66e8-x86_64-unknown-linux-gnu
bisector-ci-381e9ef09effbed5f1378a24dc6e461fea35a0e1-x86_64-unknown-linux-gnu
bisector-ci-3b1b0ef4d80d3117924d91352c8b6ca528708b3c-x86_64-unknown-linux-gnu
bisector-ci-3bc6ea5673e3e292db1e5b6ecaaaa883ca5af0b8-x86_64-unknown-linux-gnu
bisector-ci-3c9faa0d037b9eecda4a440cc482ff7f960fb8a5-x86_64-unknown-linux-gnu
bisector-ci-3d461af2a23456a2676aadb13b4253c87bdfe28d-x86_64-unknown-linux-gnu
bisector-ci-3f2a5921a451378f219edec28810f5f2f45cf1be-x86_64-unknown-linux-gnu
bisector-ci-3f808f29e6f5efa56b6e2270e8715a38dfc34b4d-x86_64-unknown-linux-gnu
bisector-ci-487b4d8a4426049036cc484b15254bea5e70316c-x86_64-unknown-linux-gnu
bisector-ci-4c37f6d78c9c83e05caa0d1e43ce7d0c3f27538e-x86_64-unknown-linux-gnu
bisector-ci-4f08307f6efdbca86d27beecd257fad9913192e9-x86_64-unknown-linux-gnu
bisector-ci-57ef8d642d21965304bde849bab4f389b4353e27-x86_64-unknown-linux-gnu
bisector-ci-59484a8c8f57188e6983b79076d532a57a646494-x86_64-unknown-linux-gnu
bisector-ci-595f14b02216a127df89326d03a7f4e22cd4067f-x86_64-unknown-linux-gnu
bisector-ci-5d04477ea8118ba54d9ce402848dda19a41d61eb-x86_64-unknown-linux-gnu
bisector-ci-61795d52b042dc5f1ac65d82489e6e362104c84a-x86_64-unknown-linux-gnu
bisector-ci-6647be93640686a2a443a49f15c3390b68c8b5dd-x86_64-unknown-linux-gnu
bisector-ci-69b78537fac74de40f009b076bcbbf54b77683ad-x86_64-unknown-linux-gnu
bisector-ci-6a979b3e32522049d0acb4a47f7ae44b7c8abfd5-x86_64-unknown-linux-gnu
bisector-ci-71e00273c0921e1bc850ae8cc4161fbb44cfa848-x86_64-unknown-linux-gnu
bisector-ci-72b21e1a64dbbbb3b59ac7ce21363c366a894b79-x86_64-unknown-linux-gnu
bisector-ci-74c974e80bb1591613822c77adde78e4e6b4f4ea-x86_64-unknown-linux-gnu
bisector-ci-74d03a92c6be7c97317cee466136ba41677065bd-x86_64-unknown-linux-gnu
bisector-ci-75b9d89c68a4a92758349272aa4e35a8eb7a6708-x86_64-unknown-linux-gnu
bisector-ci-7bee525095c0872e87c038c412c781b9bbb3f5dc-x86_64-unknown-linux-gnu
bisector-ci-844264adda6f41ca6d0d61c4bcac0f263fc5072f-x86_64-unknown-linux-gnu
bisector-ci-873b4beb0cc726493b94c8ef21f68795c04fbbc1-x86_64-unknown-linux-gnu
bisector-ci-878603b4734bc24bd4b95742c1d5918ec215bdd8-x86_64-unknown-linux-gnu
bisector-ci-9e79395f92bff6a8f536430e42a4beae69f60ff8-x86_64-unknown-linux-gnu
bisector-ci-a33907a7a5381473eec8bcfa0c56e05a856a911c-x86_64-unknown-linux-gnu
bisector-ci-a423f68a0d75656eabab4982a06bed9f316f7109-x86_64-unknown-linux-gnu
bisector-ci-a63150b9cb14896fc22f9275c32682423de94d48-x86_64-unknown-linux-gnu
bisector-ci-b2fabe39bde5174e8d728bb85f2b8d0572c35b74-x86_64-unknown-linux-gnu
bisector-ci-b49ecc9eb70a51e89f32a7358e790f7b3808ccb3-x86_64-unknown-linux-gnu
bisector-ci-b5fd2a5b8fa814c5b66236dae4aaf6c47ba91c7a-x86_64-unknown-linux-gnu
bisector-ci-c1995621a44398ac33ab368adbfb69753218b49e-x86_64-unknown-linux-gnu
bisector-ci-c5b4d121f7a0fd3fa1367cd53c3b96f9f16a67c9-x86_64-unknown-linux-gnu
bisector-ci-c86564c412a5949088a53b665d8b9a47ec610a39-x86_64-unknown-linux-gnu
bisector-ci-ce0bf0b22b646bacf91f73393483f684a44848ca-x86_64-unknown-linux-gnu
bisector-ci-d1c79458b5d13bd0179d7dbafd5ca4ea9ae3e6aa-x86_64-unknown-linux-gnu
bisector-ci-d3877ec33269edb7355ef8538d1cc5d157aa1ace-x86_64-unknown-linux-gnu
bisector-ci-d9563937fa3b030c5845811113505070109414d2-x86_64-unknown-linux-gnu
bisector-ci-e0b00b9e19cab02d6d50674b38d640a91833faf5-x86_64-unknown-linux-gnu
bisector-ci-ebe9eca11c5f639e1adc43360c099615c0351159-x86_64-unknown-linux-gnu
bisector-ci-ec818fda361ca216eb186f5cf45131bd9c776bb4-x86_64-unknown-linux-gnu
bisector-ci-f02672cb8bffef88934d31d9044257a4d11e5d1f-x86_64-unknown-linux-gnu
bisector-ci-f21b4c0888ca6a388fcf9365fc0044fa0642ab98-x86_64-unknown-linux-gnu
bisector-ci-f403dee04e6a801fe0f49a9c351fcd2ae8edd37c-x86_64-unknown-linux-gnu
bisector-ci-f532b1cca87e16b6a76d793fd2c0ea4a14536e04-x86_64-unknown-linux-gnu
bisector-ci-f6fbaa16f5e846d908c98aeb8e15865f94987f82-x86_64-unknown-linux-gnu
bisector-ci-f8463896a9b36a04899c013bd8825a7fd29dd7a4-x86_64-unknown-linux-gnu
bisector-ci-f9e7961506a97b318ad4815b8ce94bb045562f89-x86_64-unknown-linux-gnu
bisector-ci-fb23dd3c6b120f0d2e55e5f2c69a464df7b35fdf-x86_64-unknown-linux-gnu
bisector-ci-fef627b1ebdc7369ddf8a4031a5d25733ac1fb34-x86_64-unknown-linux-gnu
bisector-nightly-2020-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-05-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-13-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-15-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-16-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-17-x86_64-unknown-linux-gnu
bisector-nightly-2020-10-22-x86_64-unknown-linux-gnu
bisector-nightly-2020-11-08-x86_64-unknown-linux-gnu
bisector-nightly-2020-12-13-x86_64-unknown-linux-gnu
bisector-nightly-2021-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2021-02-21-x86_64-unknown-linux-gnu
bisector-nightly-2021-07-11-x86_64-unknown-linux-gnu
bisector-nightly-2021-08-14-x86_64-unknown-linux-gnu
bisector-nightly-2021-08-31-x86_64-unknown-linux-gnu
bisector-nightly-2021-09-01-x86_64-unknown-linux-gnu
bisector-nightly-2021-09-02-x86_64-unknown-linux-gnu
bisector-nightly-2021-09-04-x86_64-unknown-linux-gnu
bisector-nightly-2021-09-09-x86_64-unknown-linux-gnu
bisector-nightly-2021-09-18-x86_64-unknown-linux-gnu
bisector-nightly-2021-11-27-x86_64-unknown-linux-gnu
bisector-nightly-2022-04-16-x86_64-unknown-linux-gnu
bisector-nightly-2023-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2023-01-20-x86_64-unknown-linux-gnu
bisector-nightly-2023-07-17-x86_64-unknown-linux-gnu
bisector-nightly-2023-10-06-x86_64-unknown-linux-gnu
bisector-nightly-2023-10-08-x86_64-unknown-linux-gnu
bisector-nightly-2023-10-15-x86_64-unknown-linux-gnu
bisector-nightly-2023-10-17-x86_64-unknown-linux-gnu
bisector-nightly-2023-11-12-x86_64-unknown-linux-gnu
bisector-nightly-2023-11-22-x86_64-unknown-linux-gnu
bisector-nightly-2023-11-29-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-08-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-10-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-12-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-17-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-19-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-25-x86_64-unknown-linux-gnu
bisector-nightly-2023-12-28-x86_64-unknown-linux-gnu
bisector-nightly-2024-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2024-01-30-x86_64-unknown-linux-gnu
bisector-nightly-2024-02-01-x86_64-unknown-linux-gnu
bisector-nightly-2024-02-08-x86_64-unknown-linux-gnu
bisector-nightly-2024-02-12-x86_64-unknown-linux-gnu
bisector-nightly-2024-02-25-x86_64-unknown-linux-gnu
bisector-nightly-2024-03-06-x86_64-unknown-linux-gnu
bisector-nightly-2024-03-09-x86_64-unknown-linux-gnu
bisector-nightly-2024-04-09-x86_64-unknown-linux-gnu
bisector-nightly-2024-04-21-x86_64-unknown-linux-gnu
bisector-nightly-2024-05-04-x86_64-unknown-linux-gnu
bisector-nightly-2024-05-29-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-07-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-09-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-13-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-14-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-17-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-18-x86_64-unknown-linux-gnu
bisector-nightly-2024-07-28-x86_64-unknown-linux-gnu
bisector-nightly-2024-08-01-x86_64-unknown-linux-gnu
bisector-nightly-2024-08-10-x86_64-unknown-linux-gnu
bisector-nightly-2024-08-22-x86_64-unknown-linux-gnu
bisector-nightly-2024-09-04-x86_64-unknown-linux-gnu
bisector-nightly-2024-10-12-x86_64-unknown-linux-gnu
bisector-nightly-2024-10-23-x86_64-unknown-linux-gnu
bisector-nightly-2024-10-24-x86_64-unknown-linux-gnu
bisector-nightly-2024-11-28-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-12-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-20-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-22-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-26-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-27-x86_64-unknown-linux-gnu
bisector-nightly-2024-12-28-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-03-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-12-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-15-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-18-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-19-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-20-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-21-x86_64-unknown-linux-gnu
bisector-nightly-2025-01-26-x86_64-unknown-linux-gnu
bisector-nightly-2025-02-16-x86_64-unknown-linux-gnu
bisector-nightly-2025-02-21-x86_64-unknown-linux-gnu
bisector-nightly-2025-02-24-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-05-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-08-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-09-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-11-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-12-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-13-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-14-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-16-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-18-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-20-x86_64-unknown-linux-gnu
bisector-nightly-2025-03-23-x86_64-unknown-linux-gnu
bisector-nightly-2025-04-01-x86_64-unknown-linux-gnu
bisector-nightly-2025-04-13-x86_64-unknown-linux-gnu
bisector-nightly-2025-04-19-x86_64-unknown-linux-gnu
bisector-nightly-2025-04-25-x86_64-unknown-linux-gnu
bisector-nightly-2025-04-26-x86_64-unknown-linux-gnu
bisector-nightly-2025-06-01-x86_64-unknown-linux-gnu
bisector-nightly-2025-06-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-06-09-x86_64-unknown-linux-gnu
bisector-nightly-2025-06-12-x86_64-unknown-linux-gnu
bisector-nightly-2025-06-29-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-15-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-18-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-20-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-21-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-22-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-25-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-26-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-29-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-30-x86_64-unknown-linux-gnu
bisector-nightly-2025-07-31-x86_64-unknown-linux-gnu
bisector-nightly-2025-08-01-x86_64-unknown-linux-gnu
bisector-nightly-2025-08-02-x86_64-unknown-linux-gnu
bisector-nightly-2025-08-05-x86_64-unknown-linux-gnu
bisector-nightly-2025-08-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-09-15-x86_64-unknown-linux-gnu
bisector-nightly-2025-10-11-x86_64-unknown-linux-gnu
bisector-nightly-2025-10-14-x86_64-unknown-linux-gnu
bisector-nightly-2025-10-15-x86_64-unknown-linux-gnu
bisector-nightly-2025-10-16-x86_64-unknown-linux-gnu
bisector-nightly-2025-10-17-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-01-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-04-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-06-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-07-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-08-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-10-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-11-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-13-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-15-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-16-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-17-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-18-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-19-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-21-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-22-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-23-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-26-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-27-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-28-x86_64-unknown-linux-gnu
bisector-nightly-2025-11-30-x86_64-unknown-linux-gnu
bisector-nightly-2025-12-11-x86_64-unknown-linux-gnu
bisector-nightly-2025-12-13-x86_64-unknown-linux-gnu
bisector-nightly-2025-12-14-x86_64-unknown-linux-gnu
bisector-nightly-2025-12-25-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-01-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-02-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-05-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-07-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-08-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-09-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-16-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-18-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-20-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-22-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-23-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-29-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-30-x86_64-unknown-linux-gnu
bisector-nightly-2026-01-31-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-02-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-03-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-04-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-05-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-08-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-09-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-10-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-11-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-12-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-13-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-14-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-15-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-16-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-17-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-18-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-20-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-23-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-25-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-26-x86_64-unknown-linux-gnu
bisector-nightly-2026-02-28-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-02-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-03-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-05-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-08-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-10-x86_64-unknown-linux-gnu
bisector-nightly-2026-03-11-x86_64-unknown-linux-gnu
master

active toolchain
----------------
name: nightly-x86_64-unknown-linux-gnu
active because: it's the default toolchain
installed targets:
  x86_64-unknown-linux-gnu
```

### OS version

```console
6.18.12-1-MANJARO
```

<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->

### PR DESCRIPTION
**Pull request by Cloud0310**
Fix #4759 with dynamic name width.

### CODE REVIEW

**Comment by Cloud0310** [comment]
image

The formatted result would be like this.
Still, I don't have an good way to test out whether the fix on `rustup update` instantly (after tormorrow's nightly build is out I could test out this?).
For now, I added a const var for default minimal name width with value 15.
And for the illustrated component of `llvm-bitcode-linker` (19 chars) in the picture, the name length scaled as wished.

Thanks @rami3l for helping me out on this small issue here.

File: src/dist/download.rs [hunk 1]
```diff
@@ -343,9 +348,16 @@ pub(crate) struct DownloadStatus {
     /// bar would reappear immediately, not allowing the user to correctly see the message,
     /// before the progress bar starts again.
     retry_time: Mutex<Option<Instant>>,
+    /// The dynamic maximum width of the component names for alignment
+    name_width: usize,
 }
 
 impl DownloadStatus {
+    fn style(&self, suffix: &str) -> ProgressStyle {
```
Comment (rami3l) [inline src/dist/download.rs]: Nit: Consider extracting this to a standalone function and to be used above as well, since the only dependency on `&self` is `self.name_width()`.

You can make this clearer by extracting this function in the first commit which is separate from other changes with a fix `named_width = 13`, and then add the `name_width` parameter.

File: src/dist/manifestation.rs [hunk 2]
```diff
@@ -408,7 +419,7 @@ impl Manifestation {
             .unwrap()
             .replace(DEFAULT_DIST_SERVER, dl_cfg.tmp_cx.dist_server.as_str());
 
-        let status = dl_cfg.status_for("rust");
+        let status = dl_cfg.status_for("rust", 15);
```
Comment (rami3l) [inline src/dist/manifestation.rs]: I think given the fact that the only component name is "rust" in v1, we'd just do:

```rs
let component = "rust"; let status = dl_cfg.status_for(component, component.len());
```

File: src/dist/manifestation.rs [hunk 3]
```diff
@@ -153,11 +153,22 @@ impl Manifestation {
             }
         }
 
+        const DEFAULT_MIN_NAME_WIDTH: usize = 15;
+        let max_name_width = update
+            .components_to_install
+            .iter()
+            .map(|component| new_manifest.short_name(component).len())
```
Comment (rami3l) [inline src/dist/manifestation.rs:170]: Nit: This implementation implicitly relied on the fact that `.short_name()` will be used in `ComponentBinary` for the component name.

Suggest extracting a function `ComponentBinary::(component: Component, manifest: &'a Manifest)` and use that on both sides instead.

**Review by rami3l — COMMENTED** [review]
Looks great in general modulo some tiny nits. Thanks a lot for helping out!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustup/4768/bf429b1ff981c9c28474b9b17f77b98811215a1e..9db1f40c37f989cc23700e06ef7afb6132018905)*

File: src/dist/download.rs [hunk 4]
```diff
@@ -285,11 +285,15 @@ impl<'a> DownloadCfg<'a> {
...
+    pub(crate) fn status_for(
+        &self,
+        component: impl Into<Cow<'static, str>>,
+        name_width: usize,
+    ) -> DownloadStatus {
         let progress = ProgressBar::hidden();
         progress.set_style(
             ProgressStyle::with_template(
-                "{msg:>13.bold} downloading [{bar:15}] {total_bytes:>11} ({bytes_per_sec}, ETA: {eta})",
+                &format!("{{msg:>{}.bold}} downloading [{{bar:15}}] {{total_bytes:>11}} ({{bytes_per_sec}}, ETA: {{eta}})", name_width)
```
Comment (rami3l) [inline src/dist/download.rs]: Nit: I think it's clearer to use the new style `format!()` both here and in other places, e.g. `"{{msg:>{name_width}.bold}} ...`

**Comment by FranciscoTGouveia** [comment]
> Still, I don't have an good way to test out whether the fix on `rustup update` instantly (after tormorrow's nightly build is out I could test out this?)

If you change the hash in `.rustup/update-hashes/<some-toolchain>` and remove the `.rustup/toolchains/<some-toolchain>/lib/rustlib/multirust-channel-manifest.toml`, you can force an update of that toolchain.

**Comment by Cloud0310** [comment]
@rami3l Thanks for your code style suggestions, I refactored the code, and tested with @FranciscoTGouveia method.
image
Seems to me everything is fine?

**Review by rami3l — COMMENTED** [review]
The overall logic looks fine to me now. Nice!

It must be noted though, in terms of history manipulation in nontrivial rustup PRs like this, it will require some more work to be done.

Basically we use atomic commits here so if there's one refactoring plus one new feature in the total list of changes that'd be two commits (and preferably refactoring comes first).

I suggest you do the same thing with this PR: split it into one or two refactoring PRs beforehand, and finally introduce the new feature. After that we can go back to the implementation details.

Many thanks in advance 🙏 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustup/4768/dfc31fe32f67f5f105ab99267027810213fe4e97..dfb927b51724edf43d179ec595dfd786835416a6)*

File: src/dist/download.rs [hunk 5]
```diff
@@ -334,6 +339,11 @@ impl DownloadTracker {
     }
 }
 
+fn create_named_style(name_width: usize, suffix: &str) -> ProgressStyle {
```
Comment (djc) [inline src/dist/download.rs]: I think it would make more sense to attach this method to `DownloadStatus`, since it depends on its `name_width` field. It should be the last function in the `impl` block.

File: src/dist/download.rs [hunk 6]
```diff
@@ -334,6 +339,11 @@ impl DownloadTracker {
...
+    let template = format!("{{msg:>{}.bold}} {}", name_width, suffix);
```
Comment (djc) [inline src/dist/download.rs]: Nit: inline the format argument name for `suffix`.

File: src/dist/manifestation.rs [hunk 7]
```diff
@@ -749,18 +761,22 @@ struct ComponentBinary<'a> {
 }
 
 impl<'a> ComponentBinary<'a> {
+    fn get_name(component: &Component, manifest: &Manifest) -> String {
```
Comment (djc) [inline src/dist/manifestation.rs]: - This shouldn't be attached to `ComponentBinary`, since it doesn't use its state.
- This shouldn't yield `String` since some of its callers don't need an owned value.
- Avoid `get_()` prefixes per the [API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

File: src/dist/manifestation.rs [hunk 8]
```diff
@@ -416,7 +427,8 @@ impl Manifestation {
             .unwrap()
             .replace(DEFAULT_DIST_SERVER, dl_cfg.tmp_cx.dist_server.as_str());
 
-        let status = dl_cfg.status_for("rust");
+        let component_name = "rust";
```
Comment (djc) [inline src/dist/manifestation.rs:432]: Nit: binding this value seems pointless?

Comment (rami3l) [reply src/dist/manifestation.rs:432]: @djc I suggested this because it's not entirely clear to write `dl_cfg.status_for("rust", 4)`

File: src/dist/manifestation.rs (hunk 7 above)
Comment (rami3l) [reply src/dist/manifestation.rs]: @djc I think a separate extracted function would be useful since in a later commit the same function will be used to calculate the maximal length, and the contributor should be extra clear as not to use anything other than `.short_name()`.

Thus I consider it reasonable to attach this to `ComponentBinary` since it's used by it for the `name` in `.status_for()`, but maybe you have a better solution?

File: src/dist/download.rs [hunk 9]
```diff
@@ -346,6 +348,11 @@ pub(crate) struct DownloadStatus {
 }
 
 impl DownloadStatus {
+    fn create_progress_style(suffix: &str) -> ProgressStyle {
```
Comment (rami3l) [inline src/dist/download.rs]: Similar to https://github.com/rust-lang/rustup/pull/4768/changes/8ad6c4103ed581508f25d16c5a4cfcc798e590d7#r2986716135, the `create_` prefix is redundant and should be removed.

File: src/dist/download.rs [hunk 10]
```diff
@@ -345,14 +353,11 @@ pub(crate) struct DownloadStatus {
     /// bar would reappear immediately, not allowing the user to correctly see the message,
     /// before the progress bar starts again.
     retry_time: Mutex<Option<Instant>>,
+    /// The dynamic maximum width of the component names for alignment
+    name_width: usize,
 }
 
 impl DownloadStatus {
-    fn create_progress_style(suffix: &str) -> ProgressStyle {
```
Comment (rami3l) [inline src/dist/download.rs]: Once determined the location to add, the newly-introduced function should only be added once throughout the commit history of this PR.

File: src/dist/manifestation.rs (hunk 8 above)
Comment (djc) [reply src/dist/manifestation.rs:432]: Fair enough!

File: src/dist/download.rs (hunk 9 above)
Comment (Cloud0310) [reply src/dist/download.rs]: Thanks for the tip. Already fixed in latest commit.

Comment (rami3l) [reply src/dist/download.rs]: @Cloud0310 Not in the latest commit though; it should be in the first commit 🙏 
Also, the commit message of the first commit must be rewritten to reflect the new name.

File: src/dist/manifestation.rs (hunk 7 above)
Comment (djc) [reply src/dist/manifestation.rs]: I don't like associated functions that don't use a type's state. IMO for that case it's better to just have a free function, since it's pretty much unrelated to `ComponentBinary`.

File: src/dist/download.rs [hunk 11]
```diff
@@ -346,6 +348,11 @@ pub(crate) struct DownloadStatus {
 }
 
 impl DownloadStatus {
+    fn progress_style(suffix: &str) -> ProgressStyle {
```
Comment (djc) [inline src/dist/download.rs]: Nit: this should go at the bottom of the impl block.

File: src/dist/manifestation.rs (hunk 7 above)
Comment (djc) [reply src/dist/manifestation.rs]: Also, this is a one-liner with 3 call sites by the end of this PR -- I would probably not add a wrapper for it at all. (Also, it allocates, which is unnecessary for at least one of the 3 call sites.)

Comment (rami3l) [reply src/dist/manifestation.rs]: That's fair. I'd still consider it practical to just add a comment saying "you should match this function to calculate the length bla-bla-bla" because the implicit contract exists anyway. Would you be okay with that?

Comment (djc) [reply src/dist/manifestation.rs]: Not entirely sure what you mean.

Comment (rami3l) [reply src/dist/manifestation.rs]: @djc Sorry for not being clear enough previously. You are definitely right about the allocation thing, but essentially I would like to find a way to make it clear in this change that:

- The `ComponentBinary` type has a certain way to convert the component to a display string. The current version happens to be using `.short_name()` but that's an implementation detail of the abstraction itself.

- When calculating the name padding (which happens to be outside of `ComponentBinary`) we have to follow the implicit contract of using the same way to get the maximal length. OTOH if a later contributor goes for `.to_string()` etc for the said conversion there might be a mismatch. It'd be useful if they can be warned about it.

Comment (djc) [reply src/dist/manifestation.rs]: That's fair. I'd be okay with keeping a free function to make sure there's only one way to do it, but I don't think it should be attached to `ComponentBinary` and I don't think it should allocate.

Comment (Cloud0310) [reply src/dist/manifestation.rs]: I personally like the idea of remove this func, the only implicit call of it is the max_name_width calculation (overall, the func is only called 3 times, not worth it).

My idea: Just remove this abstraction, make the call of `new_manifest::short_name` clear with a comment indicating implicit dependency of `ComponentBinary`'s internal implementation.

Final result would be like:
```rust
const DEFAULT_MIN_NAME_WIDTH: usize = 13;
let max_name_width = update
            .components_to_install
            .iter()
            // Get the final re-mapped name used within ComponentBinary, See `ComponentBinary::new` for implicit dependency
            .map(|component| new_manifest.short_name(component).len())
            .max()
            .unwrap_or(0)
            .max(DEFAULT_MIN_NAME_WIDTH);
```

Or go with @rami3l 's idea is also ok with me.

Comment (rami3l) [reply src/dist/manifestation.rs]: @Cloud0310 I'm okay with that, let's do this for now.

You _could_ make it clearer by saying something like "this length must be the same as the component name's length used in `ComponentBinary::new`". That's more concise I think.

**Comment by Cloud0310** [comment]
Fixed the default copy behavior with `Component::name()`.
Waiting for further discussion on how should this function be in the final patch. :)

File: src/dist/manifestation.rs (hunk 7 above)
Comment (Cloud0310) [reply src/dist/manifestation.rs]: > @Cloud0310 I'm okay with that, let's do this for now.
> 
> You _could_ make it clearer by saying something like "this length must be the same as the component name's length used in `ComponentBinary::new`". That's more concise I think.

Final code here:
```rust
const DEFAULT_MIN_NAME_WIDTH: usize = 13;
let max_name_width = update
    .components_to_install
    .iter()
    // The same as the component name's length used in `ComponentBinary::new`
    // As it's used for status output
    .map(|component| new_manifest.short_name(component).len())
    .max()
    .unwrap_or(0)
    .max(DEFAULT_MIN_NAME_WIDTH);
```

@djc would you like this implementation?

File: src/dist/download.rs [hunk 12]
```diff
@@ -346,6 +348,11 @@ pub(crate) struct DownloadStatus {
...
+        let template = format!("{{msg:>{}.bold}} {}", 13, suffix);
```
Comment (rami3l) [inline src/dist/download.rs]: Use new-style formatting here:

```rs
let template = format!("{{msg:>13.bold}} {suffix}");
```

File: src/dist/download.rs [hunk 13]
```diff
@@ -345,11 +348,13 @@ pub(crate) struct DownloadStatus {
...
     retry_time: Mutex<Option<Instant>>,
+    /// The dynamic maximum width of the component names for alignment
+    name_width: usize,
 }
 
 impl DownloadStatus {
-    fn progress_style(suffix: &str) -> ProgressStyle {
-        let template = format!("{{msg:>{}.bold}} {}", 13, suffix);
+    fn progress_style(name_width: usize, suffix: &str) -> ProgressStyle {
+        let template = format!("{{msg:>{}.bold}} {suffix}", name_width);
```
Comment (rami3l) [inline src/dist/download.rs]:
```rs
let template = format!("{{msg:>{name_width}.bold}} {suffix}");
```

**Review by rami3l — APPROVED** [review]

File: src/dist/download.rs (hunk 12 above)
Comment (rami3l) [reply src/dist/download.rs]: @Cloud0310 I still want to keep the history clean so even this line is changed in the second commit, in the first commit you are still expected to address all nits. Thanks :)

File: src/dist/download.rs (hunk 11 above)
Comment (Cloud0310) [reply src/dist/download.rs]: Ok, got confused when re-writing history. :heart:

File: src/dist/manifestation.rs (hunk 7 above)
Comment (rami3l) [reply src/dist/manifestation.rs]: Looks good to me, let's merge it like this first :)

**Comment by rami3l** [comment]
@Cloud0310 Thanks again for the contribution :)
