### PR TITLE
fix(rustup-mode)!: don't install toolchain on `rustup --version`

### LINKED ISSUE #1397: `rustup show` should not force-install the default toolchain if it is not installed.
This behavior confused me:

```
$ rustup uninstall nightly-2018-04-01-x86_64-apple-darwin
info: uninstalling toolchain 'nightly-2018-04-01-x86_64-apple-darwin'
info: toolchain 'nightly-2018-04-01-x86_64-apple-darwin' uninstalled
$ rustup show
Default host: x86_64-apple-darwin

info: syncing channel updates for 'nightly-2018-04-01-x86_64-apple-darwin'
info: latest update on 2018-04-01, rust version 1.26.0-nightly (517f24025 2018-03-31)
info: downloading component 'rustc'
 57.3 MiB /  57.3 MiB (100 %)   7.8 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 46.2 MiB /  46.2 MiB (100 %)   7.4 MiB/s ETA:   0 s                
info: downloading component 'cargo'
  3.0 MiB /   3.0 MiB (100 %)   1.5 MiB/s ETA:   0 s                
info: downloading component 'rust-docs'
  6.8 MiB /   6.8 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-i686-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-2018-04-01-x86_64-apple-darwin (directory override for '/Users/user/GitHub/unrust')
rustc 1.26.0-nightly (517f24025 2018-03-31)
```

Is `rustup show` supposed to actually start installing components? I was under the impression that it was just for listing out what you have installed.

I'm on a macOS 10.12.6 host.

### PR DESCRIPTION
**Pull request by rami3l**
Supersedes #2658.

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -694,17 +694,17 @@ impl<'a> Cfg<'a> {
...
             trace!("Fetching rustc version from toolchain `{}`", t);
             self.set_toolchain_override(&ResolvableToolchainName::try_from(&t[1..])?);
         }
 
         Ok(self
-            .find_or_install_active_toolchain()
-            .await?
-            .0
-            .rustc_version())
+            .find_active_toolchain()?
```
Comment (djc) [inline src/config.rs]: How do you feel about this alternative?

```rust
-        Ok(self
-            .find_active_toolchain()?
-            .map(|(name, _)| Toolchain::new(self, name))
-            .transpose()?
-            .map(|toolchain| toolchain.rustc_version()))
+        Ok(match self.find_active_toolchain()? {
+            Some((name, _)) => Some(Toolchain::new(self, name)?.rustc_version()),
+            None => None,
+        })
```

File: src/cli/rustup_mode.rs [hunk 2]
```diff
@@ -548,11 +548,10 @@ pub async fn main(current_dir: PathBuf, process: &Process) -> Result<utils::Exit
             info!("This is the version for the rustup toolchain manager, not the rustc compiler.");
             let mut cfg = common::set_globals(current_dir, false, true, process)?;
             match cfg.active_rustc_version() {
-                Ok(Some(version)) => info!("The currently active `rustc` version is `{}`", version),
+                Ok(Some(version)) => info!("The currently active `rustc` version is `{version}`"),
                 Ok(None) => info!("No `rustc` is currently active"),
                 Err(err) => trace!(
-                    "Wanted to tell you the current rustc version, too, but ran into this error: {}",
-                    err
+                    "Wanted to tell you the current `rustc` version, but ran into this error: {err}",
```
Comment (djc) [inline src/cli/rustup_mode.rs]: Since you're changing this, maybe also make this a little less familiar? Like "Wanted to tell you the current rustc version" -> "Failed to display the current rustc version"?

**Review by djc — APPROVED** [review]
Nice!

File: src/config.rs (hunk 1 above)
Comment (rami3l) [reply src/config.rs]: @djc Now that I think about it, I guess let-else would be a better alternative.

File: src/cli/rustup_mode.rs (hunk 2 above)
Comment (rami3l) [reply src/cli/rustup_mode.rs]: @djc Makes sense. There's a certain amount of "fun" in the original wording and it's a bit hard to determine how much of that "fun" we'd like to have in our project...

Comment (rami3l) [reply src/cli/rustup_mode.rs]: @djc Done.

File: src/config.rs (hunk 1 above)
Comment (rami3l) [reply src/config.rs]: @djc Changed to

```rust
let Some((name, _)) = self.find_active_toolchain()? else {
    return Ok(None);
};
Ok(Some(Toolchain::new(self, name)?.rustc_version()))
```

Comment (djc) [reply src/config.rs]: Nice!

**Review by djc — APPROVED** [review]
