### PR TITLE
fix(config): warn if host is incompatible with the toolchain in `rustup default`

### LINKED ISSUE #3972: `rustup default` doesn't show proper warning when architecture is not compatible
Fresh install rustup on my Windows Subsystem for Linux, choose `stable-x86_64-apple-darwin` toolchain
after installation, run `rustc` it reports `~/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc: 1: Syntax error: "(" unexpected`

Or if you choose `stable-x86_64-pc-windows-gnu`, run `rustc` after installation,
it reports `error: the 'rustc' binary, normally provided by the 'rustc' component, is not applicable to the 'stable-x86_64-pc-windows-gnu' toolchain`

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3972:

> FWIW we do emit this warning for `rustup toolchain install`:
> 
> https://github.com/rust-lang/rustup/blob/4207838d962204123f70705ff9f3e73c37b813df/src/cli/rustup_mode.rs#L820-L825
> 
> ```console
> > uname -mrs
> Darwin 23.5.0 arm64
> 
> > rustup toolchain install stable-unknown-linux-gnu --profile=minimal
> error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain.
> warn: toolchain 'stable-unknown-linux-gnu' may not be able to run on this system.
> warn: If you meant to build software to target that platform, perhaps try `rustup target add aarch64-unknown-linux-gnu` instead?
> info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
> info: latest update on 2024-07-25, rust version 1.80.0 (051478957 2024-07-21)
> info: downloading component 'cargo'
> info: downloading component 'rust-std'
> ^C⏎                           
> ```
> 
> ... it could be that this is not covered by `rustup default` somehow. So adding the same warning to that path should address this issue.

_https://github.com/rust-lang/rustup/issues/3972#issuecomment-2266332004_
            
A unified `ensure_installed()` function also paves the way to addressing #2686.

### CODE REVIEW

File: src/cli/common.rs [hunk 1]
```diff
@@ -633,6 +634,22 @@ pub(crate) fn ignorable_error(
...
+/// Warns if rustup is trying to install a toolchain that might not be
+/// able to run on the host system.
+pub(crate) fn warn_if_host_is_incompatible(
+    toolchain: impl Display,
+    host_arch: &TargetTriple,
+    target_triple: &TargetTriple,
+    force_non_host: bool,
+) -> Result<()> {
+    if !force_non_host && !host_arch.can_run(target_triple)? {
+        error!("DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain.");
```
Comment (rami3l) [inline src/cli/common.rs]: I actually don't think this is a good way forward, since `host_arch.can_run()` relies on hardcoding and is fragile. The warnings below seem sufficient.

File: src/config.rs [hunk 2]
```diff
@@ -777,40 +779,47 @@ impl<'a> Cfg<'a> {
...
-    ) -> Result<Toolchain<'_>> {
+        verbose: bool,
+    ) -> Result<(UpdateStatus, Toolchain<'_>)> {
+        if verbose {
+            (self.notify_handler)(Notification::LookingForToolchain(&toolchain));
+        }
         let components: Vec<_> = components.iter().map(AsRef::as_ref).collect();
         let targets: Vec<_> = targets.iter().map(AsRef::as_ref).collect();
-        let toolchain = match DistributableToolchain::new(self, toolchain.clone()) {
+        let profile = profile.map_or_else(|| self.get_profile(), Ok)?;
```
Comment (djc) [inline src/config.rs]: This commit has a lot going on. I'd probably recommend splitting it up in set of smaller commits, maybe like this:

* Add `tracing::instrument` attribute here
* Add notifications, contingent on `verbose` flag
* More sophisticated profile selection if not specified
* Yield status from `ensure_installed()`

For the profile thing, IMO `map_or_else()` isn't great for this case, would be clearer to use an explicit `match` here:

```rust
let profile = match profile {
    Some(profile) => profile,
    None => self.get_profile()?,
};
```

File: src/cli/common.rs [hunk 3]
```diff
@@ -15,17 +15,18 @@ use git_testament::{git_testament, render_testament};
 use tracing::{debug, error, info, trace, warn};
 
 use super::self_update;
-use crate::cli::download_tracker::DownloadTracker;
-use crate::dist::{
-    manifest::ComponentStatus, notifications as dist_notifications, TargetTriple, ToolchainDesc,
+use crate::{
```
Comment (djc) [inline src/cli/common.rs:18]: I think the import refactoring should get its own commit here is extensive enough that it merits its own commit.

File: src/cli/common.rs [hunk 4]
```diff
@@ -633,6 +634,22 @@ pub(crate) fn ignorable_error(
...
 
+/// Warns if rustup is trying to install a toolchain that might not be
+/// able to run on the host system.
+pub(crate) fn warn_if_host_is_incompatible(
+    toolchain: impl Display,
+    host_arch: &TargetTriple,
+    target_triple: &TargetTriple,
+    force_non_host: bool,
+) -> Result<()> {
+    if !force_non_host && !host_arch.can_run(target_triple)? {
```
Comment (djc) [inline src/cli/common.rs]: Invert and early return to reduce rightward drift?

File: src/cli/common.rs (hunk 1 above)
Comment (djc) [reply src/cli/common.rs]: Sounds good to me. Separate commit?

**Review by djc — COMMENTED** [review]
I like the direction here, would mainly like a cleaner commit history here to make it easier to review the details.

**Comment by rami3l** [comment]
@djc Thanks for your guidance! I'm a bit occupied with other stuff right now so I'll take another look later.

Just to be sure, ~~I actually prefer removing `--force-non-host` and the related deprecation notice~~ after [searching](https://github.com/search?q=%22--force-non-host%22&type=code) for the existing usages I think we should keep the flag itself, but remove the deprecation notice and leave the warnings as-is. Is that okay to you?

File: src/cli/common.rs (hunk 1 above)
Comment (rami3l) [reply src/cli/common.rs]: @djc Let's get the main change merged first and then discuss how to handle this detail in another issue/PR, since it looks like we already have some users who rely on this flag: https://github.com/search?q=%22--force-non-host%22&type=code

File: src/config.rs [hunk 5]
```diff
@@ -784,14 +786,18 @@ impl<'a> Cfg<'a> {
         components: Vec<String>,
         targets: Vec<String>,
         profile: Option<Profile>,
-    ) -> Result<Toolchain<'_>> {
+        verbose: bool,
+    ) -> Result<(UpdateStatus, Toolchain<'_>)> {
+        if verbose {
```
Comment (djc) [inline src/config.rs:800]: The notifications aren't mentioned in the commit message, and don't seem to be related to the return type. Separate commit?

**Review by djc — APPROVED** [review]

File: src/config.rs (hunk 5 above)
Comment (rami3l) [reply src/config.rs:800]: @djc This is very weird, could be a rebase error on my side. Will fix.

Comment (djc) [reply src/config.rs:800]: Yeah, those sometimes happen. Usually for me it happens when during a rebase I accidentally use `git commit --amend -a` when I actually meant `git rebase --continue`.

Comment (rami3l) [reply src/config.rs:800]: @djc Oh, it looks like `git absorb` has messed up my history :( I'll be more careful next time.

Comment (rami3l) [reply src/config.rs:800]: The original commit was there: https://github.com/rust-lang/rustup/commit/07777feac5e4b85846662335c541a2a57222238e

Comment (rami3l) [reply src/config.rs:800]: I cherry-picked that one out. The history should be okay now.

**Comment by rbtcollins** [comment]
> Just to be sure, I actually prefer removing --force-non-host and the related deprecation notice after [searching](https://github.com/search?q=%22--force-non-host%22&type=code) for the existing usages I think we should keep the flag itself, but remove the deprecation notice and leave the warnings as-is. Is that okay to you?

@rami3l  So the point of this was to support cross-rs properly (they need non-host toolchains), while stopping people that are just following their nose from getting stuck and confused. E.g. installing an arm64 toolchain on an amd64 machine and wondering why that breaks.

cross-rs should be updated by now I believe, so the appropriate action is to remove the warning and reject non-host toolchains unless the flag is provided.
