### PR TITLE
fix(log): use `RUSTUP_LOG` for internal `tracing` instead of `RUST_LOG`

### LINKED ISSUE #3875: Reserve `RUSTUP_LOG` for `tracing` usages instead of `RUST_LOG`
### Problem you are trying to solve

@weihanglo has raised concerns regarding `RUST_LOG` adding Rustup's log lines to `cargo run` when `cargo` is a `rustup` shim.

Cargo has changed to using `CARGO_LOG` for `cargo`-internal log lines for clarity in https://github.com/rust-lang/cargo/pull/6918, and considering the special relationship between the two projects, I think it's reasonable for us to do the same.

### Solution you'd like

Reserve `RUSTUP_LOG` for `tracing` usages inside of Rustup instead of the default `RUST_LOG`.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3875, plus some random trivial cleanups along the way.

### CODE REVIEW

File: src/currentprocess.rs [hunk 1]
```diff
@@ -256,8 +256,7 @@ impl Default for OSProcess {
 #[cfg(feature = "test")]
 pub struct TestProcess {
     pub process: Process,
-    #[allow(dead_code)] // guard is dropped at the end of the test
-    guard: DefaultGuard,
+    _guard: DefaultGuard, // guard is dropped at the end of the test
```
Comment (rami3l) [inline src/currentprocess.rs:259]: This is https://github.com/rust-lang/rustup/pull/3871#discussion_r1641254390.

Comment (djc) [reply src/currentprocess.rs:259]: Yeah -- sorry, forgot to fix that.

**Review by djc — APPROVED** [review]

File: src/currentprocess.rs (hunk 1 above)
Comment (rami3l) [reply src/currentprocess.rs:259]: @djc No worries :)
