### PR TITLE
fix(errors)!: improve error messages for `RustupError::ToolchainNotInstalled`

### LINKED ISSUE #4212: Recommended `toolchain install` command line isn't exactly right
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

In the behavior introduced in the latest release, the error message if you don't have the toolchain installed is not actually correct if your rust-toolchain.toml file formerly triggered the installation of more than just a toolchain. This is common in cross-compile situations with the `targets` key.

rustup 1.28 tells me:

```
[cbiffle@gwydion soundlaser-rs]$ cargo build
error: toolchain '1.85.0-x86_64-unknown-linux-gnu' is not installed
help: run `rustup toolchain install 1.85.0-x86_64-unknown-linux-gnu` to install it
```

...but that's not actually correct, because that does not install the `targets` listed in the toml. `cargo build` fails.

On the other hand, `rustup toolchain install` with no arguments does the right thing.

### Steps

1. Update rustup to 1.28.
2. Check out, say, https://github.com/cbiffle/soundlaser-rs
3. Make sure you don't have 1.85.0 installed.
4. Run `cargo build`.
5. Now, run the exact command from the error that displays.
6. Now, try `cargo build` again.

### Possible Solution(s)

In the event that the command is failing in a directory with a (valid) `rust-toolchain.toml`, perhaps the error message should suggest the no-argument version of `rustup toolchain install`.

### Notes

_No response_

### Rustup version

```console
rustup 1.28.0 (6e19fbec7 2025-03-02)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.85.0 (4d91de4e4 2025-02-17)`
```

### Installed toolchains

```console
Many.
```

### OS version

```console
Linux gwydion 6.9.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #4212.

### CODE REVIEW

File: src/toolchain.rs [hunk 1]
```diff
@@ -107,7 +108,10 @@ impl<'a> Toolchain<'a> {
         let path = cfg.toolchain_path(&name);
         if !Toolchain::exists(cfg, &name)? {
             return Err(match name {
-                LocalToolchainName::Named(name) => RustupError::ToolchainNotInstalled { name },
+                LocalToolchainName::Named(name) => {
+                    let is_active = matches!(cfg.active_toolchain(), Ok(Some((t, _))) if t == name);
```
Comment (rami3l) [inline src/toolchain.rs:112]: The following secretly calls `Toolchain::new()`, causing an infinite recursion.

https://github.com/rust-lang/rustup/blob/671b874c943e1f23f69adcf7b906fb1fe1077f27/src/config.rs#L704-L706

File: src/config.rs [hunk 2]
```diff
@@ -526,61 +526,30 @@ impl<'a> Cfg<'a> {
...
-                    distributable
-                        .update(&components, &targets, profile.unwrap_or_default())
-                        .await?;
-                }
-            }
-            Err(e) => return Err(e.into()),
-        };
-
-        Ok(Some(((&toolchain).into(), reason)))
+    pub(crate) fn active_toolchain(&self) -> Result<Option<(LocalToolchainName, ActiveReason)>> {
```
Comment (rami3l) [inline src/config.rs:547]: We have to extract a sync function here because v1.28.1 has made the `Cfg::find_active_toolchain()` async again, but we really need to find the active toolchain in a sync context in the commits that follow... (sigh)

Comment (rami3l) [reply src/config.rs:547]: Also, I suggest renaming `Cfg::find_active_toolchain()` to something else. Any ideas?

File: src/toolchain.rs (hunk 1 above)
Comment (rami3l) [reply src/toolchain.rs:112]: Addressed by manually inlining the call and removing unnecessary data dependencies, as stated in [`014a6d0` (#4258)](https://github.com/rust-lang/rustup/pull/4258/commits/014a6d0b8b3a3ba05666daedf04516e1266bb1cd#r2005543171).

File: src/config.rs (hunk 2 above)
Comment (ChrisDenton) [reply src/config.rs:547]: To be honest I'm struggling to think of a good name.

File: src/config.rs [hunk 3]
```diff
@@ -526,61 +526,33 @@ impl<'a> Cfg<'a> {
...
-            Ok(mut distributable) => {
-                if !distributable.components_exist(&components, &targets)? {
-                    distributable
-                        .update(&components, &targets, profile.unwrap_or_default())
-                        .await?;
-                }
-            }
-            Err(e) => return Err(e.into()),
-        };
+        match self.find_or_install_active_toolchain(true, false).await {
```
Comment (rami3l) [inline src/config.rs:538]: This has also exposed an existing bug in v1.28.1 that `Cfg::find_active_toolchain()` ignores `--force-non-host` at all. Will fix.

File: src/config.rs (hunk 2 above)
Comment (rami3l) [reply src/config.rs:547]: @ChrisDenton I'm currently thinking about something like:

| Before | After | Remarks |
|---|---|---|
| find_active_toolchain() | maybe_ensure_active_toolchain() | Dispatches to one of the following (async) |
| find_active_toolchain() (old implementation in 1.28.0) | active_toolchain() | Queries the active toolchain (sync) |
| find_or_install_active_toolchain() | ensure_active_toolchain() | Ensures the installation of the active toolchain (async) |

... how does that sound?

Comment (ChrisDenton) [reply src/config.rs:547]: That sounds good to me. I think those names do make the relationship between them clearer to me at least.

File: src/cli/rustup_mode.rs [hunk 4]
```diff
@@ -763,7 +763,7 @@ async fn default_(
             }
         };
 
-        if let Some((toolchain, reason)) = cfg.maybe_ensure_active_toolchain(None).await? {
+        if let Some((toolchain, reason)) = cfg.active_toolchain()? {
```
Comment (rami3l) [inline src/cli/rustup_mode.rs:766]: Since we're just emitting an `info!()`, there's no need to install anything.

**Review by ChrisDenton — APPROVED** [review]
lgtm, thanks!

File: src/config.rs [hunk 5]
```diff
@@ -526,61 +526,33 @@ impl<'a> Cfg<'a> {
...
-
         let should_install_active = if let Some(force) = force_install_active {
             force
         } else {
             self.should_auto_install()?
         };
-
         if !should_install_active {
-            return Ok(Some(((&toolchain).into(), reason)));
+            return self.active_toolchain();
```
Comment (rami3l) [inline src/config.rs:535]: If `should_install_active` is set to `false`, we return `self.active_toolchain()` which was the old behavior of `find_active_toolchain()` in v1.28.0, corresponding to the last 2 early-returning branch of the previous `match` that gets deleted in this change:

https://github.com/rust-lang/rustup/blob/e2d9e7edde6ee1a79e6e44f3b81065443c1fc6eb/src/config.rs#L517-L528

File: src/config.rs [hunk 6]
```diff
@@ -526,61 +526,33 @@ impl<'a> Cfg<'a> {
...
         }
 
-        let components = components.iter().map(AsRef::as_ref).collect::<Vec<_>>();
```
Comment (rami3l) [inline src/config.rs:559]: If `should_install` is set to `true`, we delegate the installation to `find_or_install_active_toolchain()` which has the same logic:

https://github.com/rust-lang/rustup/blob/e2d9e7edde6ee1a79e6e44f3b81065443c1fc6eb/src/config.rs#L758-L765
https://github.com/rust-lang/rustup/blob/e2d9e7edde6ee1a79e6e44f3b81065443c1fc6eb/src/config.rs#L813-L844

File: src/config.rs [hunk 7]
```diff
@@ -675,17 +675,13 @@ impl<'a> Cfg<'a> {
 
                     // XXX: this awkwardness deals with settings file being locked already
                     let toolchain_name = toolchain_name.resolve(&default_host_triple)?;
-                    match Toolchain::new(self, (&toolchain_name).into()) {
```
Comment (rami3l) [inline src/config.rs:706]: I have manually inlined `Toolchain::new()` here and removed the statement causing an infinite recursion, because it was not needed; in fact, to allow any `RustupError::ToolchainNotInstalled` to happen with this call, the toolchain must not exist:

https://github.com/rust-lang/rustup/blob/f9edccde032ea3109e0b78c891dd74852c0b25ff/src/toolchain.rs#L106-L115
