### PR TITLE
fix(toolchain): forbid toolchain names starting with `+`

### LINKED ISSUE #4571: Error for `rustup run +stable cargo check` is misleading
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

As a user used to `+toolchain`, it can be easy to accidentally do that with `cargo run` but the error you get doesn't communicate that problem:
```console
$ rustup run +stable cargo check
error: toolchain '+stable' is not installed
```

### Steps

1. Run `rustup run +stable cargo -h`

### Possible Solution(s)

If `+` is reserved from being a leading character in toolchains: focus the error around the `+` prefix syntax being unsupported and provide a help message saying to drop it

If `+` is allowed as a leading character in toolchains: Check for a `+` prefix` and add a note saying that the `+` prefix syntax isn't used here and it can be dropped if thats the users intent

### Notes

_No response_

### Rustup version

```console
rustup 1.28.2 (e4f3ad6f8 2025-04-28)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/epage/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (active, default)
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
nightly-2023-11-13-x86_64-unknown-linux-gnu
nightly-2024-06-03-x86_64-unknown-linux-gnu
nightly-2024-09-10-x86_64-unknown-linux-gnu
nightly-2024-10-19-x86_64-unknown-linux-gnu
nightly-2025-01-27-x86_64-unknown-linux-gnu
nightly-2025-04-02-x86_64-unknown-linux-gnu
nightly-2025-06-26-x86_64-unknown-linux-gnu
1.0.0-x86_64-unknown-linux-gnu
1.48-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu
1.56.0-x86_64-unknown-linux-gnu
1.57.0-x86_64-unknown-linux-gnu
1.58.0-x86_64-unknown-linux-gnu
1.60.0-x86_64-unknown-linux-gnu
1.64-x86_64-unknown-linux-gnu
1.64.0-x86_64-unknown-linux-gnu
1.65-x86_64-unknown-linux-gnu
1.65.0-x86_64-unknown-linux-gnu
1.66-x86_64-unknown-linux-gnu
1.66.0-x86_64-unknown-linux-gnu
1.70-x86_64-unknown-linux-gnu
1.70.0-x86_64-unknown-linux-gnu
1.71-x86_64-unknown-linux-gnu
1.71.0-x86_64-unknown-linux-gnu
1.71.1-x86_64-unknown-linux-gnu
1.72-x86_64-unknown-linux-gnu
1.74-x86_64-unknown-linux-gnu
1.75-x86_64-unknown-linux-gnu
1.76-x86_64-unknown-linux-gnu
1.80-x86_64-unknown-linux-gnu
1.80.1-x86_64-unknown-linux-gnu
1.81-x86_64-unknown-linux-gnu
1.83-x86_64-unknown-linux-gnu
1.83.0-x86_64-unknown-linux-gnu
1.84-x86_64-unknown-linux-gnu
1.85-x86_64-unknown-linux-gnu
1.86-x86_64-unknown-linux-gnu
1.86.0-x86_64-unknown-linux-gnu
1.88-x86_64-unknown-linux-gnu
1.89-x86_64-unknown-linux-gnu
1.90-x86_64-unknown-linux-gnu
stage1

active toolchain
----------------
name: stable-x86_64-unknown-linux-gnu
active because: it's the default toolchain
installed targets:
  aarch64-apple-darwin
  i686-unknown-linux-gnu
  i686-unknown-linux-musl
  powerpc-unknown-linux-gnu
  wasm32-unknown-unknown
  x86_64-pc-windows-gnu
  x86_64-pc-windows-msvc
  x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl
  x86_64-unknown-none
```

### OS version

```console
Linux dross 6.16.3-76061603-generic #202508231538~1758561135~22.04~171c8de SMP PREEMPT_DYNAMIC Mon S x86_64 x86_64 x86
_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by cachebag**
Users accidentally use `+stable` with `rustup run`; in this PR we now forbid toolchain names starting with `+` globally.

closes #4571

### CODE REVIEW

File: src/toolchain/names.rs [hunk 1]
```diff
@@ -67,6 +67,8 @@ pub enum InvalidName {
     ToolchainPath(String),
     #[error("invalid toolchain name '{0}'")]
     ToolchainName(String),
+    #[error("toolchain '{0}' is not installed\nhelp: remove the '+' prefix: `rustup run {1} ...`")]
```
Comment (cachebag) [inline src/toolchain/names.rs]: I didn't know how verbose or concise this should have been. I'm happy to change it if it's not quite what we want.

**Review by djc — APPROVED** [review]
This makes sense to me, thanks!

File: src/toolchain/names.rs [hunk 2]
```diff
@@ -302,6 +304,12 @@ impl ResolvableLocalToolchainName {
 
     /// Validates if the string is a resolvable toolchain, or a path based toolchain.
     fn validate(candidate: &str) -> Result<Self, InvalidName> {
+        if let Some(without_plus) = candidate.strip_prefix('+') {
+            return Err(InvalidName::PlusPrefix(
+                candidate.to_string(),
```
Comment (rami3l) [inline src/toolchain/names.rs]: Nit: It seems that there's no need to store `+stable` and `stable` in two separate strings, only the latter would be enough?

**Review by rami3l — DISMISSED** [review]

**Comment by rami3l** [comment]
@djc Just confirming, currently it's far from common but we do allow toolchain names with the `+` prefixes right? I don't see anything about that in `rustup toolchain link --help` so I assume it's still valid.

If that is the case, then it's possible that we need to raise this error later in the pipeline, only when a toolchain with the said name is not found?

> As a user used to `+toolchain`, it can be easy to accidentally do that with `cargo run` but the error you get doesn't communicate that problem:
> 
> $ rustup run +stable cargo check
> error: toolchain '+stable' is not installed
_#4571_

**Comment by djc** [comment]
From what I'm seeing `+` prefixes are only specifically supported at the top level (in both rustup and proxy mode). I definitely don't recall any details but I think I'm comfortable with the risk of these changes.

**Comment by rami3l** [comment]
> From what I'm seeing `+` prefixes are only specifically supported at the top level (in both rustup and proxy mode). I definitely don't recall any details but I think I'm comfortable with the risk of these changes.

@djc Sorry for not being clear enough previously, but what I wanted to say is about the edge case of a toolchain name starting with `+`, say `+foo`, so that the calls would be written as `cargo ++foo ...`.

I know this sounds crazy and should be banned in https://github.com/rust-lang/rustup/issues/4059, but IIRC for now such names are still valid 😓

```console
> rustup run +foo cargo
error: toolchain '+foo' is not installed

> rustup ++foo show
Default host: aarch64-apple-darwin
[...]
error: toolchain '+foo' is not installed
```

... totally coherent 😱

**Comment by djc** [comment]
Ahh. Let's not worry about it and/or ban it now?

**Review by rami3l — CHANGES_REQUESTED** [review]
@djc Yeah, why not? I'd expect this breakage will be relatively small and nearly no one will actually notice it.

@cachebag How about just banning all toolchain names starting with `+` right now?

Instead of the current changes, put the general part in the `fn validate(candidate: &str) -> Result<&str, InvalidName>;` function (that's where common rules are defined), ~~and put the hint specific to #4571 in `rustup run`~~ and just suggest using the toolchain name without that prefix, without being specific to `rustup run`.

**Review by rami3l — APPROVED** [review]
Many thanks! I'm okay with this as long as the name of the commit and the PR is changed to reflect the latest changes, say `` forbid toolchain names starting with `+` ``.

@djc What do you think?

**Comment by cachebag** [comment]
> forbid toolchain names starting with `+`

Does this also steer from the original issue at hand?

**Comment by rami3l** [comment]
Hmmm the original error message was confusing but made sense exactly because `+` has been permitted at the beginning of the toolchain names... So I won't call this a deviation.

Also, given the current error message, it should be easy to deduce that a toolchain name is expected as the positional argument here, rather than the `+`-prefixed form.

Besides, I think this is also an opportunity for us to test out what toolchain names are actually used so at least we'd have some expectation of what can be broken.

Finally, this could allow smarter guesses to happen, since we are sure that the `+` prefix here is not conveying any particular intention.

- For example, when `stable` is installed we can eventually issue something like: "`+stable` is not a valid toolchain name, did you mean `stable`?" which IMHO would be a great follow-up to do.

**Review by rami3l — APPROVED** [review]

**Comment by rami3l** [comment]
As I already said, this looks good to me as long as @djc feels the same. However we could potentially use more prudence in merging yet another breaking change between beta and stable... I'd currently prefer playing the safe card and postpone this to the upcoming 2.0 👀

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
> However we could potentially use more prudence in merging yet another breaking change between beta and stable... I'd currently prefer playing the safe card and postpone this to the upcoming 2.0 👀

I mean, do you have a concrete plan for 2.0? When will that be released? I still think the version number is not going to make much difference in how much testing/caution people exercise before/when upgrading.

**Comment by rami3l** [comment]
> I mean, do you have a concrete plan for 2.0? When will that be released? I still think the version number is not going to make much difference in how much testing/caution people exercise before/when upgrading.

@djc Thank you for this constructive question.

I'm sorry but I'm not sure if we are on the same page here; I think my stance with breaking changes will not change significantly whether the next non-patch release will be `1.30` or `2.0`, as it is in theory more dangerous after a beta release has been cut.

Of course, in terms of actual impact this should be considered a minor breakage, so I'm also okay with merging this patch immediately, as long as enough attention has been drawn. Your call!

**Comment by djc** [comment]
Given the amount of response on internals I have no reason to feel the beta has resulted in a substantial amount of testing. Maybe we should do a post to the Inside Rust blog?

**Comment by rami3l** [comment]
> Given the amount of response on internals I have no reason to feel the beta has resulted in a substantial amount of testing. Maybe we should do a post to the Inside Rust blog?

@djc Yes, that's a good idea! I'll take care of it.

Besides, after giving this PR another look, I think I'm probably worrying too much again over a small change that can be easily reverted in the next patch release. My apologies!
