### PR TITLE
fix(windows): update `DisplayVersion` on `rustup self update`

### LINKED ISSUE #3739: rustup self update doesn't update DisplayVersion
### Problem

When updating rustup from a prior release using `rustup update`, the DisplayVersion in the registry isn't updated from the old release version. This will result in tools like winget thinking rustup is outdated, and might confuse users.

### Steps

1. Install an older release of rustup that sets DisplayVersion such as 1.26.0
2. Run `rustup update`, and check that rustup is updated to the latest version
3. Open the "Uninstall a program" menu in control panel or check `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Rustup` in the registry to see the outdated version number

### Possible Solution(s)

Maybe `do_add_to_programs` isn't called for updates? I haven't checked the code yet.

### Notes

Related to #3047 and #3055

### Rustup version

```console
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.0 (aedd173a2 2024-03-17)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\User\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.77.0 (aedd173a2 2024-03-17)
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3739.

My daily driver is a Mac (and OpenSSL refuses to cross-build here) so this is pretty much a best-effort blind fix.

cc @ChrisDenton 

## Concerns

- [x] ~~Is it necessary to add a test case for this one? If so, how? (Considering the sandboxing requirements, doing this properly might be hard.)~~ A sandboxed test case has been added.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
This looks fine to me. I do wonder if failure should be a warning instead of an error? It's not technically critical to the update process, though it is important to inform the user of it.

File: tests/suite/cli_self_upd.rs [hunk 1]
```diff
@@ -304,7 +304,24 @@ info: downloading self-update
             &["rustup", "self", "update"],
             &format!("  rustup updated - {version} (from {version})\n\n",),
```
Comment (rami3l) [inline tests/suite/cli_self_upd.rs:308]: This is a bit weird since in this test `version` appears 2 times (so they are the same thing?), and technically my addition can produce a false negative if the `DisplayVersion` is somehow not updated. However I cannot think of a better place to add it... We could possibly change the `DisplayVersion` before `rustup self update` to be sure, but that breaks the sandboxing.

Comment (rami3l) [reply tests/suite/cli_self_upd.rs:308]: I chose to remove the `DisplayVersion` and see if `rustup self update` re-adds it. This also breaks the sandbox but in a more harmless way, I expect.

File: src/cli/self_update.rs [hunk 2]
```diff
@@ -1128,6 +1125,10 @@ pub(crate) fn update(cfg: &Cfg) -> Result<utils::ExitCode> {
     Ok(utils::ExitCode(0))
 }
 
+fn get_and_parse_new_rustup_version(path: &Path) -> Option<String> {
```
Comment (rbtcollins) [inline src/cli/self_update.rs:1135]: I'm not sure this one-off function carries its own weight.

```
  let Some(version) = get_new_rustup_version(&setup_path).map(parse_new_rustup_version) else {...}
```

doesn't have enough complexity, reusability, or cyclomatic complexity to worry about

File: src/cli/self_update/windows.rs [hunk 3]
```diff
@@ -500,13 +500,23 @@ pub(crate) fn do_remove_from_path() -> Result<()> {
...
+    Ok(RegKey::predef(HKEY_CURRENT_USER)
+        .create_subkey(RUSTUP_UNINSTALL_ENTRY)
+        .context("Failed creating uninstall key")?
+        .0)
+}
+
+pub(crate) fn do_update_programs_display_version(version: &str) -> Result<()> {
+    rustup_uninstall_reg_key()?
+        .set_value("DisplayVersion", &version)
+        .context("Failed to set display version")
```
Comment (rbtcollins) [inline src/cli/self_update/windows.rs]: perhaps either DisplayVersion (as it is a concrete thing) or

`Failed to record version for uninstall` (as this is the conceptual layer)

File: src/cli/self_update.rs (hunk 2 above)
Comment (rbtcollins) [reply src/cli/self_update.rs:1135]: nvm I see its reused

File: tests/suite/cli_self_upd.rs [hunk 4]
```diff
@@ -304,7 +304,38 @@ info: downloading self-update
...
+
+    update_setup(&|config, _| {
+        config.expect_ok(&["rustup-init", "-y", "--no-modify-path"]);
+
+        winreg::RegKey::predef(winreg::enums::HKEY_CURRENT_USER)
+            .create_subkey(RUSTUP_UNINSTALL_ENTRY)
+            .unwrap()
+            .0
+            .delete_value("DisplayVersion")
+            .unwrap();
```
Comment (rbtcollins) [inline tests/suite/cli_self_upd.rs]: That deletes, not overwrites, thus it tests introducing, not replacing.

I suggest setting the value to a an old release of rustup rather than deleting

Comment (rami3l) [reply tests/suite/cli_self_upd.rs]: @rbtcollins You are right and I intended to do so, it's just that this test modifies a global state (the winreg). This hasn't been done before, so I'm not sure what is considered proper use of winreg in the tests... Leaving a (realistic enough) placeholder in an intermediate state seems weird to me.

Ideally, if this test fails midway, the user should be able to immediately identify that `DisplayVersion` is a placeholder.

File: src/cli/self_update/windows.rs (hunk 3 above)
Comment (rami3l) [reply src/cli/self_update/windows.rs]: @rbtcollins That's the original error message. But I agree we can change it, ideally in another commit than the refactoring.

Comment (rami3l) [reply src/cli/self_update/windows.rs]: Done.

File: tests/suite/cli_self_upd.rs (hunk 4 above)
Comment (rami3l) [reply tests/suite/cli_self_upd.rs]: I've chosen `9.999.99`. Hopefully it's clear enough that this is not a real version number.

**Review by djc — APPROVED** [review]

**Review by rami3l — COMMENTED** [review]
I think it'll still be better to let @rbtcollins decide whether my response is satisfying and whether this PR is ready to be merged :)

File: tests/suite/cli_self_upd.rs (hunk 4 above)
Comment (rbtcollins) [reply tests/suite/cli_self_upd.rs]: @rami3l oh indeed; we have isolation for such tests already.

Probably this test needs to be reworked - sorry, brain not fully switched on. see https://github.com/rust-lang/rustup/blob/master/src/cli/self_update/test.rs#L38 - thats the core helper, and

https://github.com/search?q=repo%3Arust-lang%2Frustup%20with_saved_path&type=code

which shows it being used in both unit tests and integration tests.

I have no strong view about whether your choice of an integration test or unit is better - though a considerable preference for unit testing rather than integration tests.

Anyhow, what is needed is to extend that helper, or write a similar one, to manage the application uninstall data, and then use that in the test

Comment (rami3l) [reply tests/suite/cli_self_upd.rs]: > I have no strong view about whether your choice of an integration test or unit is better - though a considerable preference for unit testing rather than integration tests.

@rbtcollins Regarding this particular case I do think integration test is better since we're ensuring the resolution of that issue (i.e. the correct behavior is exposed to the end user). The current `self update` implementation is a bit convoluted and it took me quite a while to figure out where exactly to add the code modifying `DisplayVersion`... 

> Anyhow, what is needed is to extend that helper, or write a similar one, to manage the application uninstall data, and then use that in the test

Will do.

Comment (rami3l) [reply tests/suite/cli_self_upd.rs]: @rbtcollins Done.

File: src/cli/self_update/test.rs [hunk 5]
```diff
@@ -1,57 +1,85 @@
...
+#[cfg(windows)]
+fn restore_path(p: Option<RegValue>) {
+    restore_reg_value(&RegKey::predef(HKEY_CURRENT_USER), "Environment", "PATH", p)
+}
+
 #[cfg(unix)]
 fn restore_path(_: Option<()>) {}
+
+#[cfg(windows)]
+pub fn with_saved_programs_display_version(f: &mut dyn FnMut()) {
```
Comment (rami3l) [inline src/cli/self_update/test.rs]: Looking back, it could be that this is overly specific for `rustup`'s public API.

We could possibly expose `with_saved_reg_value(root, subkey, name, callback)` instead, and `with_saved_programs_display_version(callback)` can then be easily defined on the tests side by pinning these arguments.

File: src/cli/self_update/test.rs [hunk 6]
```diff
@@ -1,57 +1,85 @@
...
+}
+
+#[cfg(windows)]
+pub fn get_path() -> io::Result<Option<RegValue>> {
+    get_reg_value(&RegKey::predef(HKEY_CURRENT_USER), "Environment", "PATH")
+}
+
 #[cfg(unix)]
-pub fn get_path() -> std::io::Result<Option<()>> {
+pub fn get_path() -> io::Result<Option<()>> {
```
Comment (rami3l) [inline src/cli/self_update/test.rs]: Also, this does nothing on Unix according to `rust-analyzer`: it's not even referenced once. It's probably better to make it Windows-exclusive.

File: src/cli/self_update/test.rs (hunk 5 above)
Comment (rbtcollins) [reply src/cli/self_update/test.rs]: This is in the test API anyway, so I don't see any issue.
