### PR TITLE
fix(rustup-mode): return `ExitCode(1)` when `update()` fails

### LINKED ISSUE #3476: When `rustup update` fails, it doesn't return an exit code that indicate failure
### Problem

When `rustup update` fails, it doesn't return an exit code that indicate failure but instead returns 0.

### Steps

1. Be in a situation where `rustup update` fails, for example by disabling your network connection
2. Run `rustup update`
3. The command returns the exit code 0, or success

### Possible Solution(s)

Return an exit code different than 0 in case of failure

### Notes

_No response_

### Rustup version

```console
rustup 1.26.0 (2023-05-04)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0 (5680fa18f 2023-08-23)`
```

### Installed toolchains

```console
Not relevant
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3476, verified via local testing.

### CODE REVIEW

File: src/cli/rustup_mode.rs [hunk 1]
```diff
@@ -862,10 +864,10 @@ async fn update(cfg: &mut Cfg<'_>, opts: UpdateOpts) -> Result<utils::ExitCode>
             }
         }
         if self_update {
-            common::self_update(|| Ok(utils::ExitCode(0)), cfg.process).await?;
+            common::self_update(|| Ok(()), cfg.process).await?;
         }
     } else {
-        common::update_all_channels(cfg, self_update, opts.force).await?;
+        exit_code = exit_code.and(common::update_all_channels(cfg, self_update, opts.force).await?);
```
Comment (rami3l) [inline src/cli/rustup_mode.rs]: @djc Since `ExitCode::and` essentially simulates `&&` in bash, how about overriding `ops::BitAnd*`, and this will become a pretty standard `&=`?

File: src/utils/utils.rs [hunk 2]
```diff
@@ -24,6 +24,16 @@ pub use crate::utils::utils::raw::{is_file, path_exists};
 #[derive(Debug, PartialEq, Eq)]
 pub struct ExitCode(pub i32);
 
+impl ExitCode {
+    pub fn and(self, other: Self) -> Self {
+        if self == Self(0) {
+            other
+        } else {
+            self
+        }
```
Comment (djc) [inline src/utils/utils.rs]: Maybe rewrite this as

```rust
match self.0 == 0 {
    true => other,
    false => self,
}
```

**Review by djc — APPROVED** [review]
This seems okay. Personally I feel like use of the custom `ExitCode` is a bad abstraction. One idea I've played with is that we should change types to be `Result<T, Option<E>>`, where the `Some` represents an error that should be yielded by the top-level caller while `None` means the error has already been reported. (We then report `ExitCode::FAILURE` if the `Result` is `Err`.)

**Comment by rami3l** [comment]
> This seems okay. Personally I feel like use of the custom `ExitCode` is a bad abstraction. One idea I've played with is that we should change types to be `Result<T, Option<E>>`, where the `Some` represents an error that should be yielded by the top-level caller while `None` means the error has already been reported. (We then report `ExitCode::FAILURE` if the `Result` is `Err`.)

@djc Indeed, in other projects that I've worked with my principle is that we should never expose the exit code with the single exception of the main module, where some `thiserror` is converted to `ExitStatus` via an `impl Termination`.

But that kind of change is clearly out of the scope of this PR...

File: src/utils/utils.rs (hunk 2 above)
Comment (rami3l) [reply src/utils/utils.rs]: > Maybe rewrite this as
> 
> ```rust
> match self.0 == 0 {
>     true => other,
>     false => self,
> }
> ```

@djc I don't like `match bool` very much personally, but there's a middle ground I guess we can all accept:

```rust
match self.0 {
  0 => other,
  _ => self,
}
```

Comment (djc) [reply src/utils/utils.rs]: Ah yeah, that is even better!

File: src/cli/rustup_mode.rs (hunk 1 above)
Comment (djc) [reply src/cli/rustup_mode.rs]: Seems okay.

File: src/utils/utils.rs [hunk 3]
```diff
@@ -24,6 +25,25 @@ pub use crate::utils::utils::raw::{is_file, path_exists};
 #[derive(Debug, PartialEq, Eq)]
 pub struct ExitCode(pub i32);
 
+impl BitAnd for ExitCode {
+    type Output = Self;
+
+    fn bitand(self, rhs: Self) -> Self::Output {
+        match self.0 {
```
Comment (djc) [inline src/utils/utils.rs:33]: Maybe add a short comment explaining the conceptual logic?

```
// If `self` is `0` (success), yield `other`
```

(Also for the other impl.)

**Review by djc — APPROVED** [review]

File: src/utils/utils.rs (hunk 3 above)
Comment (rami3l) [reply src/utils/utils.rs:33]: @djc Done!
