### PR TITLE
fix(cli/self-update): fix output format for `rustup check` on TTY

### LINKED ISSUE #4560: `rustup check` is missing a newline between toolchains and self
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

`rustup - Up to date : 1.28.2` is at the end of the line of the last toolchain, rather than on its own line
From `main`
Image

From release
Image

### Steps

1. Checkout `main`
2. Run `cargo run --config env.RUSTUP_FORCE_ARG0=\'rustup\' -- check`

### Possible Solution(s)

_No response_

### Notes

_No response_

### Rustup version

```console
❯ rustup --version
rustup 1.28.2 (e4f3ad6f8 2025-04-28)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.90.0 (1159e78c4 2025-09-14)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/epage/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (active, default)
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
nightly-2023-11-13-x86_64-unknown-linux-gnu
nightly-2024-06-03-x86_64-unknown-linux-gnu
nightly-2024-09-10-x86_64-unknown-linux-gnu
nightly-2024-10-19-x86_64-unknown-linux-gnu
nightly-2025-01-27-x86_64-unknown-linux-gnu
nightly-2025-04-02-x86_64-unknown-linux-gnu
nightly-2025-06-26-x86_64-unknown-linux-gnu
1.0.0-x86_64-unknown-linux-gnu
1.48-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu
1.56.0-x86_64-unknown-linux-gnu
1.57.0-x86_64-unknown-linux-gnu
1.58.0-x86_64-unknown-linux-gnu
1.60.0-x86_64-unknown-linux-gnu
1.64-x86_64-unknown-linux-gnu
1.64.0-x86_64-unknown-linux-gnu
1.65-x86_64-unknown-linux-gnu
1.65.0-x86_64-unknown-linux-gnu
1.66-x86_64-unknown-linux-gnu
1.66.0-x86_64-unknown-linux-gnu
1.70-x86_64-unknown-linux-gnu
1.70.0-x86_64-unknown-linux-gnu
1.71-x86_64-unknown-linux-gnu
1.71.0-x86_64-unknown-linux-gnu
1.71.1-x86_64-unknown-linux-gnu
1.72-x86_64-unknown-linux-gnu
1.74-x86_64-unknown-linux-gnu
1.75-x86_64-unknown-linux-gnu
1.76-x86_64-unknown-linux-gnu
1.80-x86_64-unknown-linux-gnu
1.80.1-x86_64-unknown-linux-gnu
1.81-x86_64-unknown-linux-gnu
1.83-x86_64-unknown-linux-gnu
1.83.0-x86_64-unknown-linux-gnu
1.84-x86_64-unknown-linux-gnu
1.85-x86_64-unknown-linux-gnu
1.86-x86_64-unknown-linux-gnu
1.86.0-x86_64-unknown-linux-gnu
1.88-x86_64-unknown-linux-gnu
1.89-x86_64-unknown-linux-gnu
1.90-x86_64-unknown-linux-gnu
stage1

active toolchain
----------------
name: stable-x86_64-unknown-linux-gnu
active because: it's the default toolchain
installed targets:
  aarch64-apple-darwin
  i686-unknown-linux-gnu
  i686-unknown-linux-musl
  powerpc-unknown-linux-gnu
  wasm32-unknown-unknown
  x86_64-pc-windows-gnu
  x86_64-pc-windows-msvc
  x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl
  x86_64-unknown-none
```

### OS version

```console
Linux
```

### PR DESCRIPTION
**Pull request by rami3l**
Fixes https://github.com/rust-lang/rustup/issues/4560 by manually adding a newline if multi-progress bars from `indicatif` are used.

PS: On my machine this works with or without the newline, I cannot see any difference except when resizing the window/reloading the output afterwards (this doesn't get rid of all trailing whitespaces on the final line that was supposed to push later contents to the following line).

@epage I am curious how this patch will run on your machine 👀 

@djc Could this upstream hack be an acceptable approach towards this issue, or is it better resolved on `indicatif`'s side?

### CODE REVIEW

**Comment by epage** [comment]
I'm not seeing a problem with this change.  Unfortunately, I found a bug with my own work.  If someone doesn't get to it by my tomorrow morning, I'll take a look.

**Review by djc — APPROVED** [review]

**Comment by rami3l** [comment]
@djc Thanks! Let's merge this first and see if anything gets better/worse on both @epage 's side and my side 👀

File: src/cli/rustup_mode.rs [hunk 1]
```diff
@@ -910,10 +911,17 @@ async fn check_updates(cfg: &Cfg<'_>, opts: CheckOpts) -> Result<ExitCode> {
...
+            if !has_progress_bars {
                 writeln!(t.lock(), "{message}")?;
             }
         }
+        if has_progress_bars {
+            // HACK: Add a final newline to avoid possible display issues with `indicatif` in
+            // certain terminal emulators. Currently, `indicatif` puts a series of spaces at the end
+            // of the line, forcing any output after the progress bar to be on a second line. This
+            // might not be desirable in all cases.
+            writeln!(t.lock())?;
```
Comment (FranciscoTGouveia) [inline src/cli/rustup_mode.rs:923]: What if instead we add a new progress bar to `multi_progress_bars`; wouldn't that be more idiomatic?

Comment (rami3l) [reply src/cli/rustup_mode.rs:923]: Hmmm probably?

I mean a missing newline is still definitive, only this time it's been moved from the middle to the end 🤔

I'll try this alternative and see. Thanks!

Comment (rami3l) [reply src/cli/rustup_mode.rs:923]: @FranciscoTGouveia I think I already have something, but this will require some non-trivial changes to the current code.

Also, I'm not sure if @epage's environment is more tolerant of a missing final newline or not compared to the current situation, meaning this hack might still be required if we merge self update check into the previous section.

Would you mind if I merge this first and then iterate on top of that?

Comment (FranciscoTGouveia) [reply src/cli/rustup_mode.rs:923]: SGTM!
