### PR TITLE
fix(diskio): fall back to single-threaded unpacking 

### LINKED ISSUE #3125: OOM installing rustc-dev with 1GB of memory
### Problem

I tried installing a rust toolchain in a VM I assigned 1GB of ram. (100MB used by the minimal debian install) When installing rustc-dev it got an OOM however.

### Steps

1. Create a VM
2. Assign 1GB of ram
3. Install a minimal debian system in the VM. When running it only uses 100MB of ram.
4. Attempt to install a rust toolchain with the rustc-dev component in the VM.
5. OOM

### Possible Solution(s)

I thought rustup 1.24 enabled installation on systems with little ram. Is this a regression? Would it be possible to stream the component rather than attempt to load it all at once in memory?

### Notes

For now I will be increasing the assigned amount of memory, but IMO it should be possible to install on systems with this little ram, hence this issue.

### Rustup version

```console
rustup 1.25.1 (bb60b1e89 2022-07-12)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/bjorn/.rustup

no active toolchain
```

I attempted to install nightly-2022-12-13-x86_64-unknown-linux-gnu.

### PR DESCRIPTION
**Pull request by cachebag**
When`ram_budget`< 512MB, fall back to single-threaded unpacking to avoid OOM on memory-constrained systems.

Rustup OOMs on systems with <1GB RAM because it spawns multiple I/O threads for unpacking regardless of available memory. The Threaded executor uses far more memory than its buffer pool budget tracks. This PR adds a 512MB `ram_budget` threshold below which rustup falls back to single-threaded unpacking, which peaks at ~110MB.

Fixes #3125

### CODE REVIEW

File: src/process.rs [hunk 1]
```diff
@@ -69,23 +82,23 @@ impl Process {
...
-                _ => return Ok(threads),
+                _ => return Ok(IoThreadCount::UserSpecified(threads)),
             }
         };
 
         Ok(match thread::available_parallelism() {
             // Don't spawn more than 8 I/O threads unless the user tells us to.
             // Feel free to increase this value if it improves performance.
-            Ok(threads) => Ord::min(threads.get(), 8),
+            Ok(threads) => IoThreadCount::Default(Ord::min(threads.get(), 8)),
```
Comment (djc) [inline src/process.rs]: Nit: suggest hoisting `IoThreadCount::Default(..)` out of the `match`.

File: src/process.rs [hunk 2]
```diff
@@ -31,6 +31,19 @@ mod file_source;
 mod terminal_source;
 pub use terminal_source::ColorableTerminal;
 
+pub enum IoThreadCount {
```
Comment (djc) [inline src/process.rs]: Nit: we follow top-down style, move this below its user.

File: src/diskio/mod.rs [hunk 3]
```diff
@@ -442,18 +443,45 @@ pub(crate) fn create_dir<P: AsRef<Path>>(path: P) -> io::Result<()> {
...
     }
 }
 
+fn effective_thread_count(ram_budget: usize, thread_count: IoThreadCount) -> usize {
+    match thread_count {
+        IoThreadCount::UserSpecified(n) => n,
+        IoThreadCount::Default(n) if n <= 1 => n,
+        IoThreadCount::Default(n) if ram_budget < LOW_MEMORY_THRESHOLD => {
+            warn!(
+                "Using single-threaded unpacking due to low memory \
```
Comment (djc) [inline src/diskio/mod.rs]: Nits: I think our usual style does not use capitals (and periods).

File: src/diskio/mod.rs [hunk 4]
```diff
@@ -442,18 +443,45 @@ pub(crate) fn create_dir<P: AsRef<Path>>(path: P) -> io::Result<()> {
     std::fs::create_dir(path)
 }
 
+/// The Threaded executor uses substantially more memory than its ram_budget
+/// accounts for (pool overhead, sharded_slab metadata, multiple in-flight
+/// operations, thread stacks, allocator fragmentation). On systems where the
+/// ram_budget is under this threshold, fall back to single-threaded unpacking
+/// which peaks at ~110MB.
+/// See https://github.com/rust-lang/rustup/issues/3125
+const LOW_MEMORY_THRESHOLD: usize = 512 * 1024 * 1024;
```
Comment (djc) [inline src/diskio/mod.rs]: Nit: move this to the bottom of the module, please.

**Review by djc — APPROVED** [review]
Nice, this makes sense to me!

File: src/process.rs [hunk 5]
```diff
@@ -235,6 +236,19 @@ impl Process {
     }
 }
 
+pub enum IoThreadCount {
+    Default(usize),
+    UserSpecified(usize),
+}
+
+impl IoThreadCount {
+    pub fn count(&self) -> usize {
```
Comment (rami3l) [inline src/process.rs]: This is a bit confusing to me. Why not just use [From](https://doc.rust-lang.org/std/convert/trait.From.html) and call `.into()` instead?

File: src/diskio/mod.rs [hunk 6]
```diff
@@ -445,15 +446,34 @@ pub(crate) fn create_dir<P: AsRef<Path>>(path: P) -> io::Result<()> {
...
         0 | 1 => Box::new(immediate::ImmediateUnpacker::new()),
         n => Box::new(threaded::Threaded::new(n, ram_budget)),
     }
 }
 
+fn effective_thread_count(ram_budget: usize, thread_count: IoThreadCount) -> usize {
+    match thread_count {
+        IoThreadCount::UserSpecified(n) => n,
+        IoThreadCount::Default(n) if n <= 1 => n,
+        IoThreadCount::Default(n) if ram_budget < LOW_MEMORY_THRESHOLD => {
```
Comment (rami3l) [inline src/diskio/mod.rs]: Nit: I think this predicate will be clearer like this:

```suggestion
        IoThreadCount::Default(n) if n > 1 && ram_budget < LOW_MEMORY_THRESHOLD => {
```

File: src/process.rs (hunk 5 above)
Comment (cachebag) [reply src/process.rs]: I thought that maybe the explicitness would have been helpful here

File: src/diskio/test.rs [hunk 7]
```diff
@@ -163,3 +163,34 @@ fn test_complete_file_immediate() {
...
     test_complete_file("2").unwrap()
 }
+
+#[test]
+fn test_effective_thread_count() {
+    use super::{LOW_MEMORY_THRESHOLD, effective_thread_count};
+    use crate::process::IoThreadCount::{Default, UserSpecified};
+
+    // Already single-threaded: no change regardless of budget
+    assert_eq!(effective_thread_count(32 * 1024 * 1024, Default(1)), 1);
```
Comment (rami3l) [inline src/diskio/test.rs]: Nit: Similar to `LOW_MEMORY_THRESHOLD - 1`, to convey the intent more clearly it'd probably be better to just write `LOW_MEMORY_THRESHOLD / 16`, `LOW_MEMORY_THRESHOLD / 2`, `LOW_MEMORY_THRESHOLD * 2`, etc., so that we don't need to guess what were above or below the constant.

**Review by rami3l — APPROVED** [review]
LGTM modulo one final nit (my apologies for the back and forth), and thanks again for your contribution :)
