### PR TITLE
fix(dist/linux): handle the possible unavailability of `/proc` in `rustup-init.sh`

### LINKED ISSUE #2700: `rustup-init.sh` fails to detect platform correctly under `docker buildx` which lacks `/proc`
rustup-init.sh installs the incorrect rustc and other binaries because of a failure to detect arch.
Problems: `/proc/self/exe` does not exist during docker build, so i686/386 etc is detected incorrectly as x86_64 due to failure on line 153. mips64 likely suffers the same issue because it also uses get_bitness

`grep '^Features' /proc/cpuinfo | grep -q -v neon` fails and ARMv6 is incorrectly detected as arm7 on line 367
Running the downloaded binary fails with `/lib/ld-linux-armhf.so.3: No such file or directory` (because it isnt armhf, it is armel at `/lib/ld-linux.so.3` )

Logs and example code to produce the container and error:
https://gist.github.com/miigotu/2a0b80677420d806c96d8e792ae6652e

Note: gcc inside the container reports the correct info, kernel reports x86_64
```bash
root@386c88edfbc5:/# uname -m
x86_64
root@386c88edfbc5:/# gcc -dumpmachine | sed "s/-/-$(uname -p)-/"
i686-unknown-linux-gnu
```
and
```bash
root@dac44b74e4c0:/# uname -m
armv7l
root@dac44b74e4c0:/# gcc -dumpmachine | sed "s/-/-$(uname -p)-/"
arm-unknown-linux-gnueabi
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes https://github.com/rust-lang/rustup/issues/2700. I'm no shell expert, just trying to do my best...

This fix is based on @miigotu and @kerberjg's find in https://github.com/rust-lang/rustup/issues/2700#issuecomment-1266454666 and https://github.com/rust-lang/rustup/issues/2700#issuecomment-1367488985 respectively. It first refers to `/proc/self/exe` if it's accessible, then `$SHELL` if it's set, and finally `/bin/sh`. This executable is then explicitly passed to functions that previously relied on `/proc/self/exe`.

> 有備無患 yǒu bèi wú huàn
> - to be prepared against adverse events

## Concerns

- [x] ~~What about the `grep '^Features' /proc/cpuinfo` line which also relies on `/proc`?~~ Fixed.
    - Currently, if `grep` fails (because e.g. `/proc/cpuinfo` is unavailable or malformed), we still assume `armv7`. This doesn't work in the case described in #2700, where we're using ARMv6. OTOH, falling back to `arm` is much safer in this case and will resolve the aforementioned issue.
- [x] How to test this patch?
    - ~~The `podman` instance I use seems to have `/proc` access.~~ I've tested the patch with a modified `/proc` path (`/fakeproc`) and the logic seems to work.

### CODE REVIEW

File: rustup-init.sh [hunk 1]
```diff
@@ -540,7 +540,7 @@ get_architecture() {
     # and fall back to arm.
     # See https://github.com/rust-lang/rustup.rs/issues/587.
     if [ "$_ostype" = "unknown-linux-gnueabihf" ] && [ "$_cputype" = armv7 ]; then
-        if ensure grep '^Features' /proc/cpuinfo | grep -E -q -v 'neon|simd'; then
```
Comment (rami3l) [inline rustup-init.sh:526]: Currently, if `grep` fails (because e.g. /proc/cpuinfo is unavailable or malformed), we still assume `armv7`. This doesn't work with the case described in https://github.com/rust-lang/rustup/issues/2700#issue-841531263 when we're using ARMv6.

File: rustup-init.sh [hunk 2]
```diff
@@ -356,16 +371,18 @@ get_architecture() {
...
     case "$_ostype" in
 
         Android)
             _ostype=linux-android
             ;;
 
         Linux)
-            check_proc
+            get_current_exe
+            _current_exe=$RETVAL
```
Comment (rbtcollins) [inline rustup-init.sh]: Any reason not to use

`_current_exe=get_current_exe`

**Comment by rbtcollins** [comment]
I think this looks reasonable.

There are other probes we could use, such as uname and lsb_release and gcc but they all have edge cases and caveats. One question for you then GTG IMO.

File: rustup-init.sh (hunk 2 above)
Comment (rami3l) [reply rustup-init.sh]: @rbtcollins I assume you meant `_current_exe=$(get_current_exe)`?

The `echo "Warning: ..."` calls in the function body will interfere with the function's output when it's being used like so (unless the `1>&2` trick is used, as I understand it). Looking at the surrounding code, it seems like the `$RETVAL` trick is used exactly in this case to specify the actual value to be returned.

I referred to `downloader()` as an example when writing this. This is how it calls other functions via `$RETVAL`:

https://github.com/rust-lang/rustup/blob/2a5a69e0914ff419554d684ca71eb1d72c72bcb3/rustup-init.sh#L596-L599

This is how it issues warnings:

https://github.com/rust-lang/rustup/blob/2a5a69e0914ff419554d684ca71eb1d72c72bcb3/rustup-init.sh#L604

Maybe we should use `1>&2` for `echo` commands instead? But in that case we might hit #3350, right?

File: rustup-init.sh [hunk 3]
```diff
@@ -177,12 +177,23 @@ main() {
...
+get_current_exe() {
+    # Returns the executable used for system architecture detection
     # This is only run on Linux
-    if ! test -L /proc/self/exe ; then
-        err "fatal: Unable to find /proc/self/exe.  Is /proc mounted?  Installation cannot proceed without /proc."
+    local _current_exe
+    if test -L /proc/self/exe ; then
+        _current_exe=/proc/self/exe
+    else
+        echo "Warning: Unable to find /proc/self/exe.  System architecture detection might be inaccurate."
```
Comment (rami3l) [inline rustup-init.sh]: Oops, a tiny typo here...

```suggestion
        echo "Warning: Unable to find /proc/self/exe. System architecture detection might be inaccurate."
```

File: rustup-init.sh (hunk 2 above)
Comment (rami3l) [reply rustup-init.sh]: @rbtcollins I just had another look of #3350, and I believe I should switch to `1>&2` for this function.

See https://github.com/rust-lang/rustup/issues/3350#issuecomment-2158213483 for my proposal on the direction Rustup should be moving towards in general WRT stdout/stderr handling.

Comment (rami3l) [reply rustup-init.sh]: @rbtcollins Done.

File: rustup-init.sh (hunk 3 above)
Comment (rami3l) [reply rustup-init.sh]: Done.

**Review by rbtcollins — APPROVED** [review]
