### PR TITLE
Fix #1870: Race condition with some virus scanners

### LINKED ISSUE #1870: Can't update to stable 1.35 (Windows + McAffee/Symantec)
**Problem**
`rustup update stable` fails on Windows 7 laptop with this kind of errors:
```
λ  rustup update stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2019-05-23, rust version 1.35.0 (3c235d560 2019-05-20)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-std' for 'i686-pc-windows-msvc'
info: downloading component 'rust-analysis'
info: downloading component 'rust-src'
info: downloading component 'rls'
info: downloading component 'rustfmt'
info: downloading component 'clippy'
info: removing component 'rustc'
info: removing component 'rust-std'
info: removing component 'cargo'
info: removing component 'rust-docs'
info: removing component 'rust-std' for 'i686-pc-windows-msvc'
info: removing component 'rust-analysis'
info: removing component 'rust-src'
info: removing component 'rls'
info: removing component 'rustfmt'
info: removing component 'clippy'
info: installing component 'rustc'
 60.0 MiB /  60.0 MiB (100 %)  13.9 MiB/s in 14s ETA:  0s
info: installing component 'rust-std'
 53.1 MiB /  53.1 MiB (100 %)  12.9 MiB/s in  4s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 10.3 MiB /  10.3 MiB (100 %) 401.6 KiB/s in  1m 52s ETA:  0s
info: rolling back changes
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\wxp7x5fu66ro7uib_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\b
in'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\87cu99tuet1_8jof_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\njl5zjh1vv3u_f_7_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\a3v9c1_ge4tpn6v3_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\uy_fswm9q7qled_a_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc/rust'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\yxll7wcaprlw_mik_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\e
tc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\9gl9lc_8pixiiqfg_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\e
tc/bash_completion.d'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\6t7busnax3m2avbn_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc/cargo'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\gc1cknvnskm_ezk0_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/man'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\uflb3gpv_u26533g_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/man/man1'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\73ibcu537omueytr_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/zsh'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\ya9cygapnd82_h1o_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/zsh/site-functions'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\i18s9gd8apyvbyxy_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/lib'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\d5iyjok_t9ii2dy__dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/etc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\idx95puxu1rf43da_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/bin'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\29v99sp5j0d5_ik0_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/codegen-backends'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\zb5dkerufltfrz7z_dir\rust-docs\share/doc/rust/html' to 'C:\Users\Geobomatic\.rustup\toolchains\stab
le-x86_64-pc-windows-msvc\share/doc/rust/html'
info: caused by: Access is denied. (os error 5)
```
**Steps**
1. run `rustup update stable`

**Notes**
This laptop is crap (corporate machine) and has McAffee anti virus + disk encryption installed.

With previous rustup, it was slow but it worked.

Output of `rustup --version`:
rustup 1.18.3 (435397f48 2019-05-22)
Output of `rustup show`:
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.34.2 (6c2484dc3 2019-05-13)

### PR DESCRIPTION
**Pull request by rbtcollins**
Some virus scanners take out handles on files we are going to
rename, causing access errors and preventing the rename. Typically
this is short lived. Retry rather than erroring.

No feedback given at the moment, and depends on an unreleased
retry, so WIP...

### CODE REVIEW

File: src/utils/utils.rs [hunk 1]
```diff
@@ -651,7 +654,21 @@ pub fn toolchain_sort<T: AsRef<str>>(v: &mut Vec<T>) {
...
+    // https://github.com/rust-lang/rustup.rs/issues/1870
+    // 21 fib steps from 1 sums to ~28 seconds, hopefully more than enough
+    // for our previous poor performance that avoided the race condition with
+    // McAfee and Norton.
+    retry(
+        Fibonacci::from_millis(1).map(jitter).take(21),
+        || match fs::rename(src, dest) {
+            Ok(v) => OperationResult::Ok(v),
+            Err(e) => match e.kind() {
+                io::ErrorKind::PermissionDenied => OperationResult::Retry(e),
```
Comment (kinnison) [inline src/utils/utils.rs:666]: I suppose, on a Linux system (or mac) where the `EPERM` was actually more to do with someone `chown()ing` their stuff oddly, this will end up consuming 28s before failing -- should we fail faster by making this somehow conditional on Windows?

**Review by kinnison — CHANGES_REQUESTED** [review]
Looks sound, thank you for doing the work with the `retry` crate too.

One point to address

**Comment by rbtcollins** [comment]
This will happen to wsl v1 users on windows too as they share a file system.

**Comment by kinnison** [comment]
> This will happen to wsl v1 users on windows too as they share a file system.

Accepted.

**Review by kinnison — APPROVED** [review]
If we get a green CI, this LGTM.

**Comment by kinnison** [comment]
I think the appveyor failure is spurious.
