### PR TITLE
Change default for RUSTUP_WINDOWS_PATH_ADD_BIN

### LINKED ISSUE #3036: rustup 1.25: On Windows, nested cargo invocation with a toolchain specified fails
### Problem

This is a regression in rustup 1.25 on Windows. If a program run via `cargo run` tries to run a command like `cargo +nightly ...`, it fails even if `RUSTC` is unset in the environment.

Splitting this off from https://github.com/rust-lang/rustup/issues/3031#issuecomment-1181867695 because https://github.com/rust-lang/rustup/issues/3031#issuecomment-1182253988 indicates it's a separate problem.

### Steps

https://github.com/nicholasbishop/rustup-nested-bug-repro#rustup-nested-bug-repro contains a repro of this bug.

Here's the `main.rs` of that repo:
```rust
use std::process::Command;
use std::env;

fn main() {
    // Modify the path if any argument is passed in.
    let modify_path = env::args().len() == 2;

    let mut cmd = Command::new("cargo");
    cmd.env_remove("RUSTC");
    cmd.env_remove("RUSTDOC");
    cmd.args(&["+nightly", "version"]);

    if modify_path {
        let orig_path = env::var_os("PATH").unwrap_or_default();
        let modified_split_paths = env::split_paths(&orig_path).filter(|path| {
            !path
                .components()
                .any(|component| component.as_os_str() == ".rustup")
        });
        let modified_path = env::join_paths(modified_split_paths).expect("invalid PATH");
        cmd.env("PATH", modified_path);
    }

    println!("running command: {:?}", cmd);
    let s = cmd.status().unwrap();
    assert!(s.success());
}
```

On Linux this command succeeds:

```
$ cargo run
   Compiling rustup-nested-bug-repro v0.1.0 (/var/home/nbishop/src/rustup-nested-bug-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/rustup-nested-bug-repro`
running command: "cargo" "+nightly" "version"
cargo 1.64.0-nightly (b1dd22e66 2022-07-09)
```

On Windows it fails:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\rustup-nested-bug-repro.exe`
running command: "cargo" "+nightly" "version"
error: no such subcommand: `+nightly`
thread 'main' panicked at 'assertion failed: s.success()', src\main.rs:26:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\rustup-nested-bug-repro.exe` (exit code: 101)
```

But it succeeds if the `PATH` is modified to remove toolchain entries
added by rustup:

```
$ cargo run modify
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target\debug\rustup-nested-bug-repro.exe modify`
running command: "cargo" "+nightly" "version"
cargo 1.64.0-nightly (b1dd22e66 2022-07-09)
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Rustup version

```console
$ rustup --version
rustup 1.25.0 (90365aa81 2022-06-15)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.62.0 (a8314ef7d 2022-06-27)`
```

### Installed toolchains

```console
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\nicholasbishop\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.62.0 (a8314ef7d 2022-06-27)
```

### PR DESCRIPTION
**Pull request by ehuss**
This changes the default for the RUSTUP_WINDOWS_PATH_ADD_BIN opt-in to fix the issue where adding the `bin` directory on windows was preventing recursive calls to programs like cargo from being able to use the rustup proxies.

There was a call for testing at https://internals.rust-lang.org/t/help-test-windows-behavior-between-rustup-and-cargo/20237 and https://users.rust-lang.org/t/help-test-windows-behavior-between-rustup-and-cargo/106145. AFAIK, there have not been any indications of anyone having problems.

Fixes #3036

### CODE REVIEW

**Review by rami3l — APPROVED** [review]

File: src/toolchain/toolchain.rs [hunk 1]
```diff
@@ -165,7 +165,7 @@ impl<'a> Toolchain<'a> {
         }
 
         if cfg!(target_os = "windows") {
-            // Historically rustup has included the bin directory in PATH to
+            // Historically rustup  included the bin directory in PATH to
```
Comment (djc) [inline src/toolchain/toolchain.rs]: Nit: you left a double space here.

**Review by djc — APPROVED** [review]

File: src/toolchain/toolchain.rs (hunk 1 above)
Comment (ehuss) [reply src/toolchain/toolchain.rs]: Thanks, fixed!

**Comment by cwfitzgerald** [comment]
Just raising that this seems to have broken `cargo-nextest`  ([issue](https://github.com/nextest-rs/nextest/issues/1493)) whenever there are proc-macro crates in the test suite. I don't know the details involved or which end this should be fixed on, just wanted to make the issue visible here. It seems like the nextest people have a way to fix it on their end, and setting RUSTUP_WINDOWS_PATH_ADD_BIN=1 in env allows things to work in the mean time, so this is non-blocking.

**Comment by smoelius** [comment]
As an additional data point, Dylint is currently [using `RUSTUP_WINDOWS_PATH_ADD_BIN=1`](https://github.com/trailofbits/dylint/commit/162fe72919bcb009fa55cf7451a7e5b9339ef4a0) to support Windows.

It may be that we could set `PATH` ourselves, but having this environment variable in `rustup` is at least a convenience.

**Comment by djc** [comment]
Can one of you open a new issue discussing what the use case here is and how/why we broke it?
