### PR TITLE
fix(utils): downgrade panic to warning in `delete_dir_contents_following_links()`

### LINKED ISSUE #4609: `rustup update` needs a cleaner error message if it fails while cleaning files - and no panic
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

`rustup update` needs a cleaner error message when it fails while cleaning files. 

PS C:\Windows\System32> rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.91.1 (ed61e7d7e 2025-11-07)

info: cleaning up downloads & tmp directories

thread 'main' panicked at src\utils\mod.rs:479:13:
Unable to clean up C:\Users\XYZ\.rustup\tmp: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Steps

run: 

rustup update

### Possible Solution(s)

_No response_

### Notes

Yesterday the whole internet went done because of a panic (thanks CloudFlare). Maybe we need to remove these unwrap()? 

### Rustup version

```console
PS C:\Windows\System32> rustup --version
rustup 1.28.2 (e4f3ad6f8 2025-04-28)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.91.1 (ed61e7d7e 2025-11-07)`
```

### Installed toolchains

```console
installed toolchains
--------------------
stable-x86_64-pc-windows-msvc (active, default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------
name: stable-x86_64-pc-windows-msvc
active because: it's the default toolchain
installed targets:
  wasm32-unknown-unknown
  x86_64-pc-windows-msvc
```

### OS version

```console
Windows 11
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #4609.

### CODE REVIEW

**Comment by djc** [comment]
Are you sure it's okay to skip cleaning up the download directory?

**Comment by rami3l** [comment]
> Are you sure it's okay to skip cleaning up the download directory?

@djc That's a good question. My rationale is this: as per

https://github.com/rust-lang/rustup/blob/a1676f4adf942c22c4a5ae58a8e30b8bb81a2029/src/dist/download.rs#L48-L51

... this directory is supposed to be owned exclusively by rustup, so rustup in theory should have full control over it, and any violation is considered an internal state violation. The same is true for the tmp dir. Given your previous analysis in https://github.com/rust-lang/rustup/issues/4609#issuecomment-3556604707, switching the control flow from divergent to non-divergent is not really harmful here and will only leave some cache in the directory, and either the cache is correct and can be reused, or it isn't and the FS writes will fail. Of course I'd be glad to be corrected.

**Comment by ChrisDenton** [comment]
If it's not OK to skip cleaning then an error would leave rustup in a broken state anyway, no?

**Comment by djc** [comment]
> If it's not OK to skip cleaning then an error would leave rustup in a broken state anyway, no?

That's fair!

File: src/utils/mod.rs [hunk 1]
```diff
@@ -435,7 +435,7 @@ pub(crate) fn delete_dir_contents_following_links(dir_path: &Path) {
 
     match raw::open_dir_following_links(dir_path).and_then(|mut p| p.remove_dir_contents(None)) {
         Err(e) if e.kind() != io::ErrorKind::NotFound => {
-            panic!("Unable to clean up {}: {:?}", dir_path.display(), e);
+            warn!("unable to clean up {}: {e:?}", dir_path.display());
```
Comment (ChrisDenton) [inline src/utils/mod.rs]:
```suggestion
            warn!("unable to clean up {}: {e}", dir_path.display());
```

I think it'd be nicer to use the `Display` formatting for the error.

Comment (rami3l) [reply src/utils/mod.rs]: I'm not 100% sure about that since it might still be interesting to look at the underlying error in this case, and the `Display` implementation only focuses on the error message...

```rs
fn main() -> std::io::Result<()> { std::fs::File::open("foo.txt").map(drop) }
```

... this gives:

```console
> cargo run
[..]
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Returning to the example of #4609, `Os { code: 5, kind: PermissionDenied, message: "Access is denied." }` has also made the origin of the error much clearer IMHO. Otherwise it might not be immediately clear where the `Access is denied.` string is coming from?

Comment (ChrisDenton) [reply src/utils/mod.rs]: Hm, the difference is:

Before:
```
Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

After:
```
Access is denied. (os error 5)
```

I think the latter looks nicer and the only thing it's missing is the the error kind.

Comment (rami3l) [reply src/utils/mod.rs]: @ChrisDenton Okay, I'm convinced. Many thanks 🙏

**Review by ChrisDenton — APPROVED** [review]
