### PR TITLE
Stream large files during unpacking

### LINKED ISSUE #2632: "File too big" on s390x
**Problem**
On `s390x-unknown-linux-gnu`, I saw an error while installing:

```
info: profile set to 'default'
info: default host triple is s390x-unknown-linux-gnu
info: syncing channel updates for 'stable-s390x-unknown-linux-gnu'
info: latest update on 2020-12-31, rust version 1.49.0 (e1884a8e3 2020-12-29)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-std'
 11.5 MiB /  21.9 MiB ( 53 %)   0 B/s in  1s ETA: Unknown                                                          21.9 MiB /  21.9 MiB (100 %)  11.5 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
error: error: 'File too big rustc-1.49.0-s390x-unknown-linux-gnu/rustc/lib/librustc_driver-d57ba40a74a3b9c1.so 220354152'
 11.0 MiB /  53.4 MiB ( 21 %)   0 B/s in  1s ETA: Unknown                                                          23.7 MiB /  53.4 MiB ( 44 %)  11.0 MiB/s in  2s ETA:  2s                                                          34.6 MiB /  53.4 MiB ( 65 %)  11.8 MiB/s in  3s ETA:  1s                                                          44.1 MiB /  53.4 MiB ( 83 %)  11.5 MiB/s in  4s ETA:  0s                                                          53.4 MiB /  53.4 MiB (100 %)  11.0 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-s390x-unknown-linux-gnu'

  stable-s390x-unknown-linux-gnu installed - rustc 1.49.0 (e1884a8e3 2020-12-29)


Rust is installed now. Great!
```

It *seems* to work fine anyway.

**Steps**

1. Normal install on s390x: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Possible Solution(s)**
Increase `MAX_FILE_SIZE`? It seems #2363 was the most recent time...

**Notes**

Output of `rustup --version`:
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`
```

Output of `rustup show`:
```
Default host: s390x-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-s390x-unknown-linux-gnu (default)
nightly-2020-10-01-s390x-unknown-linux-gnu
nightly-2020-11-28-s390x-unknown-linux-gnu
nightly-2020-12-03-s390x-unknown-linux-gnu
nightly-2020-12-04-s390x-unknown-linux-gnu
nightly-s390x-unknown-linux-gnu

active toolchain
----------------

stable-s390x-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

Every one of those nightlies gave a similar error on `librustc_driver`.

### PR DESCRIPTION
**Pull request by rbtcollins**
Fixes #2632, #2145, #2564

Files over 16M are now written incrementally chunks rather than buffered
in memory in one full linear buffer. This chunk size is not
configurable.

For threaded unpacking, the entire memory buffer will be used to buffer
chunks and a single worker thread will dispatch IO operations from the
buffer, so minimal performance impact should be anticipated (file
size/16M round trips at worst, and most network file systems will
latency hide linear writes).

For immediate unpacking, each chunk is dispatched directly to disk,
which may impact performance as less latency hiding is possible - but
for immediate unpacking clarity of behaviour is the priority.

### CODE REVIEW

File: src/diskio/mod.rs [hunk 1]
```diff
@@ -187,6 +310,51 @@ pub fn write_file<P: AsRef<Path>, C: AsRef<[u8]>>(
     Ok(())
 }
 
+#[allow(unused_variables)]
```
Comment (kinnison) [inline src/diskio/mod.rs:313]: Why do we need this lint?

File: src/dist/component/package.rs [hunk 2]
```diff
@@ -349,36 +364,44 @@ fn unpack_without_first_dir<'a, R: Read>(
...
-                    "File too big {} {}",
-                    relpath.display(),
-                    size
-                )));
-            }
-        }
-
-        fn flush_ios(
+        /// true if either no sender_entry was provided, or the incremental file
+        /// has been fully dispatched.
```
Comment (kinnison) [inline src/dist/component/package.rs:368]: This comment makes no sense to me

**Review by kinnison — CHANGES_REQUESTED** [review]
For the most part I follow this given the conversations we have had before.  I like the CompletedIO approach to the budget reclaim, that refactor pleases me.

A couple of nit-picking whinges, and I'll be pretty happy.  I want to play a bit with this locally though too, so even if you do the cleanups now, don't merge yet.

File: src/diskio/mod.rs (hunk 1 above)
Comment (rbtcollins) [reply src/diskio/mod.rs:313]: Windows vs Linux. mode isn't used on Windows.

File: src/dist/component/package.rs (hunk 2 above)
Comment (rbtcollins) [reply src/dist/component/package.rs:368]: flush_ios returns true when either:
- sender_entry is None
- entry.read() returns Ok(0)

Rephrasing is welcome

File: src/diskio/mod.rs (hunk 1 above)
Comment (kinnison) [reply src/diskio/mod.rs:313]: :+1:

File: src/dist/component/package.rs (hunk 2 above)
Comment (kinnison) [reply src/dist/component/package.rs:368]: Sorry looks like this was me misreading the diff and thinking you'd changed *to* `Result<()>` rather than from it.  Sigh.

**Review by kinnison — APPROVED** [review]
I feel like I want to try this locally a bit, but I'm okay with merging this otherwise.
