### PR TITLE
Restore old behaviour for `rustup show active-toolchain`

### LINKED ISSUE #4217: v1.28.0 broke `rustup show active-toolchain`
### Problem

IntelliJ RustRover and scripts use `rustup show active-toolchain` to get the active toolchain name. The output is now broken as it includes a message "active because: it's the default toolchain" on a second line.
This happened in #3225.

```console
$ rustup show active-toolchain --help
Show the active toolchain

Usage: rustup[EXE] show active-toolchain [OPTIONS]

Options:
  -v, --verbose  Enable verbose output with rustc information
  -h, --help     Print help

Discussion:
    Shows the name of the active toolchain.

    This is useful for figuring out the active tool chain from
    scripts.

    You should use `rustc --print sysroot` to get the sysroot, or
    `rustc --version` to get the toolchain version.
```

> This is useful for figuring out the active tool chain from scripts.

Which is why it should output exactly the toolchain name, nothing more.

### Steps

Current output (v1.28.0):

```console
$ rustup show active-toolchain
nightly-x86_64-unknown-linux-gnu
active because: it's the default toolchain
```

Gives this chaotic error when loading any project in RustRover:
```console
Execution failed (exit code 1).
/home/sky9/.cargo/bin/cargo "+nightly-x86_64-unknown-linux-gnu
active because: it's the default toolchain" vendor --respect-source-config /home/sky9/.cache/JetBrains/RustRover2025.1/intellij-rust/stdlib/1.87.0-nightly-c16751b793dfce34909c1ba3fd1cbf4f827d7deb/vendor
    in working directory: /home/sky9/.cache/JetBrains/RustRover2025.1/intellij-rust/stdlib-local-copy/1.87.0-nightly-9375198e512f5c5ff5ae71857b1e38933ec1941d/library/sysroot
    with extra environment variables: RUSTC_BOOTSTRAP=1 TERM=ansi RUST_BACKTRACE=short RUSTC=/home/sky9/.cargo/bin/rustc
stdout: error: toolchain 'nightly-x86_64-unknown-linux-gnu
active because: it's the default toolchain' is not installed

stderr: 
```

It is trying to find a toolchain with the name `nightly-x86_64-unknown-linux-gnu\nactive because: it's the default toolchain` (with a newline in the middle) which obviously doesn't exist.

Previous output (v1.27.1 and below):
```console
$ rustup show active-toolchain
nightly-x86_64-unknown-linux-gnu (default)
```

### Possible Solution(s)

A `v1.28.1` should be released with a patch reverting just the `rustup show active-toolchain` output back to pre-1.28.0 behavior.

### Rustup version

```console
rustup 1.28.0 (6e19fbec7 2025-03-02)
```

cc @majaha @rami3l @rust-lang/rustup

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #4217

This is a very partial revert of #3225. It only restores the output of `rustup show active-toolchain` and doesn't change `--verbose` or the output of any other commands.

### CODE REVIEW

File: src/cli/rustup_mode.rs [hunk 1]
```diff
@@ -1085,18 +1085,26 @@ fn show_active_toolchain(cfg: &Cfg<'_>, verbose: bool) -> Result<utils::ExitCode
...
-                    "compiler: {}\npath: {}",
+                    "{}\nactive because: {}\ncompiler: {}\npath: {}",
+                    toolchain.name(),
+                    reason,
                     toolchain.rustc_version(),
-                    toolchain.path().display(),
+                    toolchain.path().display()
+                )?;
+            } else {
+                let reason: &dyn fmt::Display = if matches!(reason, ActiveReason::Default) {
```
Comment (djc) [inline src/cli/rustup_mode.rs]: Nit: suggest inlining the `reason` binding:

```rust
match reason {
    ActiveReason::Default => &"default"
    _ => &reason,
} as &dyn fmt::Display
```

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Thanks for picking this up!

File: src/cli/rustup_mode.rs (hunk 1 above)
Comment (ChrisDenton) [reply src/cli/rustup_mode.rs]: Oh inline is nicer. Done.
