### PR TITLE
Fix:2501 Improve post installation sourcing instructions for readability.

### LINKED ISSUE #2501: Discussion UX about sourcing env instructions for beginners (students)
Hi, 
I would like to open a discussion for improving the last part of rustup installation of rust the asking for sourcing shell env below the full details! Thanks for reading. :)

If a consensus is reached I would be happy to implement the solution.

## Situation

I used rustup to install rust with computer science bachelor two, students in semi-autonomy with docs, and message about «setting environment variable confused them». Not in a way their don't understand but in a way they don't understand that `source` is part of the full command: `source $HOME/.cargo/env` the problem repeated for 14 peoples in 2 classes so they only typed `$HOME/.cargo/env`.

But the problem is really specific that this command in bold is not seen as a command line at first glance by command line beginner.

## The message at time of writing

Right now the message is:
```
To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run source $HOME/.cargo/env ### <- this command is in bold.
```
Screenshot from 2020-09-30 09-59-35

## Suggestion to improve UX:

Maybe doing something like:

```
To configure your current shell run :
    source $HOME/.cargo/env
```
In this case a clear distinction is made between command and human instruction.

Or more terse:
```
To configure your current shell run : source $HOME/.cargo/env 
```

Thanks for reading sorry it's a raw UX feedback from teaching Rust right after making their first course of Rust, they already did racket and C language in L1 so their are not totally new to programming and linux! So i wish to open a discussion about this specific issue I observed. :)

### PR DESCRIPTION
**Pull request by AureliaDolo**
It's an atempt to fix #2501 issue.

### CODE REVIEW

**Comment by AureliaDolo** [comment]
Hello! 
@kinnison @workingjubilee what do you think about my attempt to fix #2505. 
Thanks

File: src/cli/self_update.rs [hunk 1]
```diff
@@ -166,7 +166,7 @@ To get started you need Cargo's bin directory ({cargo_home}/bin) in your `PATH`
 environment variable. Next time you log in this will be done
 automatically.
 
-To configure your current shell run `source {cargo_home}/env`
+To configure your current shell run :\n`source {cargo_home}/env`\n
```
Comment (rbtcollins) [inline src/cli/self_update.rs]: Rather than embedded `\n`'s here, just insert the extra lines you wish to show, as this is a multi-line string already.

File: src/cli/self_update.rs [hunk 2]
```diff
@@ -166,7 +166,9 @@ To get started you need Cargo's bin directory ({cargo_home}/bin) in your `PATH`
 environment variable. Next time you log in this will be done
 automatically.
 
-To configure your current shell run :\n`source {cargo_home}/env`\n
+To configure your current shell run :
+
```
Comment (jyn514) [inline src/cli/self_update.rs]: Nit: this is more whitespace than before, you only need one newline.
```suggestion
```

File: src/cli/self_update.rs [hunk 3]
```diff
@@ -191,7 +193,9 @@ macro_rules! post_install_msg_unix_no_modify_path {
 To get started you need Cargo's bin directory ({cargo_home}/bin) in your `PATH`
 environment variable.
 
-To configure your current shell run `source {cargo_home}/env`
+To configure your current shell run :
+
```
Comment (jyn514) [inline src/cli/self_update.rs]:
```suggestion
```

**Comment by AureliaDolo** [comment]
@darnuria helped me to rebase my history it should be cleaner now, I was confused by github automatic integration in review.

File: src/cli/self_update.rs [hunk 4]
```diff
@@ -166,7 +166,8 @@ To get started you need Cargo's bin directory ({cargo_home}/bin) in your `PATH`
 environment variable. Next time you log in this will be done
 automatically.
 
-To configure your current shell run `source {cargo_home}/env`
+To configure your current shell run :
+source {cargo_home}/env
```
Comment (kinnison) [inline src/cli/self_update.rs]: One point, it's common to indicate actual shell commands either with a `$` at the start of the line, or by indenting.

I would prefer:

```suggestion
    source {cargo_home}/env
```

Though if others disagree, I'm happy to merge this as-is.

Comment (rbtcollins) [reply src/cli/self_update.rs]: Indenting makes sense to me; a $ at the beginning is an antipattern as it makes copy-paste harder.

**Comment by AureliaDolo** [comment]
I added indentations for better readability and easy copy-pasting as proposed by @kinnison.

**Review by kinnison — APPROVED** [review]
From my perspective this looks good to merge.

**Comment by AureliaDolo** [comment]
It's good for me. Thanks a lot for the review. 
I rebased to keep just one commit.
