### PR TITLE
fix(utils): resolve input path in `delete_dir_contents()` if it's a link

### LINKED ISSUE #3344: Regression when ~/.rustup/downloads and/or tmp are symlinks
### Problem

```
rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ ls -ald ~/.rustup/{tmp,downloads}{/,}
lrwxrwxrwx 1 rustcargo rustcargo      37 Jun  8  2021 /home/rustcargo/.rustup/downloads -> /volatile/rustcargo/rustup/downloads/
drwxrwxr-x 2 rustcargo rustcargo    4096 May  3 12:43 /home/rustcargo/.rustup/downloads/
lrwxrwxrwx 1 rustcargo rustcargo      31 Jun  8  2021 /home/rustcargo/.rustup/tmp -> /volatile/rustcargo/rustup/tmp/
drwxrwxr-x 2 rustcargo rustcargo 1249280 May  3 12:45 /home/rustcargo/.rustup/tmp/
rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.31-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.37-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.40-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.51-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.53-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.54-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.63-x86_64-unknown-linux-gnu'
info: checking for self-update

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.69.0 (84c898d65 2023-04-16)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.70.0-beta.2 (071f14baa 2023-04-30)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.71.0-nightly (a368898de 2023-05-02)
     1.31-x86_64-unknown-linux-gnu unchanged - rustc 1.31.1 (b6c32da9b 2018-12-18)
     1.37-x86_64-unknown-linux-gnu unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
     1.40-x86_64-unknown-linux-gnu unchanged - rustc 1.40.0 (73528e339 2019-12-16)
     1.51-x86_64-unknown-linux-gnu unchanged - rustc 1.51.0 (2fd73fabe 2021-03-23)
     1.53-x86_64-unknown-linux-gnu unchanged - rustc 1.53.0 (53cb7b09b 2021-06-17)
     1.54-x86_64-unknown-linux-gnu unchanged - rustc 1.54.0 (a178d0322 2021-07-26)
     1.63-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up /home/rustcargo/.rustup/downloads: Os { code: 40, kind: FilesystemLoop, message: "Too many levels of symbolic links" }', src/utils/utils.rs:650:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

1. Make `~/.rustup/tmp` and `~/.rustup/downloads` symlinks to like-named directories elsewhere
2. Run rustup

### Possible Solution(s)

_No response_

### Notes

I assume something has changed in rustup's handling of these directories.  This used to work.  I could probably bisect it if it's not obvious.

### Rustup version

```console
rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0-beta.2 (071f14baa 2023-04-30)`
rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ 
```

### Installed toolchains

```console
rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/rustcargo/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu (default)
nightly-2018-12-19-x86_64-unknown-linux-gnu
nightly-2022-06-24-x86_64-unknown-linux-gnu
nightly-2022-11-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.31-x86_64-unknown-linux-gnu
1.37-x86_64-unknown-linux-gnu
1.40-x86_64-unknown-linux-gnu
1.51-x86_64-unknown-linux-gnu
1.53-x86_64-unknown-linux-gnu
1.54-x86_64-unknown-linux-gnu
1.63-x86_64-unknown-linux-gnu
local
stage1
1.63.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

beta-x86_64-unknown-linux-gnu (default)
rustc 1.70.0-beta.2 (071f14baa 2023-04-30)

rustcargo@zealot:/volatile/rustcargo/Rustup/Arti/arti$ 
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3344, superseding #3452:

> A better fix is to resolve the link in the calling code and then use remove_dir_contents as before.
_https://github.com/rust-lang/rustup/pull/3753#issue-2218949990_

### CODE REVIEW

File: tests/suite/cli_misc.rs [hunk 1]
```diff
@@ -702,6 +702,36 @@ fn toolchains_symlink() {
     });
 }
 
+// issue #3344
```
Comment (rbtcollins) [inline tests/suite/cli_misc.rs:705]: was this deliberately a comment line rather than doc line?

File: tests/suite/cli_misc.rs [hunk 2]
```diff
@@ -702,6 +702,36 @@ fn toolchains_symlink() {
...
+/// `~/.rustup/tmp` and `~/.rustup/downloads` are permitted to be symlinks.
+#[test]
+#[cfg(any(unix, windows))]
```
Comment (rbtcollins) [inline tests/suite/cli_misc.rs:708]: isn't this equivalent to all platforms?

File: src/utils/utils.rs [hunk 3]
```diff
@@ -611,7 +611,9 @@ where
 }
 
 pub(crate) fn delete_dir_contents(dir_path: &Path) {
```
Comment (rbtcollins) [inline src/utils/utils.rs]: this looks pretty good. I think perhaps renaming this function as well (or having a non-following-version and a following-version for callers where we don't want to escape out of our trees) would be a good idea, but I haven't checked in the code where delete_dir_contents is invoked today.

File: tests/suite/cli_misc.rs (hunk 1 above)
Comment (rami3l) [reply tests/suite/cli_misc.rs:705]: Yes, this is to be coherent with other tests above and below.

File: tests/suite/cli_misc.rs (hunk 2 above)
Comment (rami3l) [reply tests/suite/cli_misc.rs:708]: There are indeed other platforms such as wasm, although I don't know if Rustup is meaningful there or not. Similar to other tests above/below it, this one relies on the fact that we compile for Unix or Windows. I just copied the code over as I mentioned above.

Comment (djc) [reply tests/suite/cli_misc.rs:708]: Given that platforms like WASM exist, this seems okay.

File: src/utils/utils.rs (hunk 3 above)
Comment (djc) [reply src/utils/utils.rs]: The only caller is `rustup_mode::update()`, which calls this directly with `cfg.download_dir` and via `temp::Cfg`, which calls this with `temp::Cfg::root_directory`.

**Review by djc — APPROVED** [review]

File: src/utils/utils.rs (hunk 3 above)
Comment (rami3l) [reply src/utils/utils.rs]: @rbtcollins I've changed the function name accordingly.

File: src/cli/rustup_mode.rs [hunk 4]
```diff
@@ -1007,7 +1007,7 @@ fn update(cfg: &mut Cfg, m: &ArgMatches) -> Result<utils::ExitCode> {
     } else {
         common::update_all_channels(cfg, self_update, m.get_flag("force"))?;
         info!("cleaning up downloads & tmp directories");
-        utils::delete_dir_contents(&cfg.download_dir);
+        utils::delete_dir_contents_following_links(&cfg.download_dir);
```
Comment (rbtcollins) [inline src/cli/rustup_mode.rs:1010]: ok so this fine to be a symlink; its a dir only the user controls.

File: src/dist/temp.rs [hunk 5]
```diff
@@ -158,7 +158,7 @@ impl Cfg {
     }
 
     pub(crate) fn clean(&self) {
-        utils::delete_dir_contents(&self.root_directory);
+        utils::delete_dir_contents_following_links(&self.root_directory);
```
Comment (rbtcollins) [inline src/dist/temp.rs:161]: this should never be a symlink, it is created on line 105. Its probably ok to permit following links in order to get this regression fixed, but longer term we should only be deleting dirs here, since getting a symlink is impossible without someone altering state

File: tests/suite/cli_misc.rs (hunk 2 above)
Comment (rbtcollins) [reply tests/suite/cli_misc.rs:708]: I think this is a side effect of code evolution, it isn't the pattern in general, and rustup does depend on hardlinks to operate at all. Are there platforms that have hardlinks, but not symlinks?

File: src/dist/temp.rs (hunk 5 above)
Comment (rami3l) [reply src/dist/temp.rs:161]: @rbtcollins Hmmm https://github.com/rust-lang/rustup/issues/3344 explicitly mentioned the case where `tmp` is a link, so I'm not quite sure about that. BTW L105 calls `raw::ensure_dir_exists` and is actually compatible with a pre-existing link (cf. the test case).

File: tests/suite/cli_misc.rs (hunk 2 above)
Comment (rami3l) [reply tests/suite/cli_misc.rs:708]: @rbtcollins Looks like symlinks are also available on WASM/WASI: https://doc.rust-lang.org/std/os/wasi/fs/fn.symlink.html, so I'm also okay with removing this line. Anyway Rustup in its current form will fail to build on WASM and not all dependencies of this test work on WASM anyway.

File: src/dist/temp.rs (hunk 5 above)
Comment (rbtcollins) [reply src/dist/temp.rs:161]: You added a regression test for that, so empirical validatation of whether its the one or not should be quite easy. I don't think it is as this is the tmp root for one dist operation, not the dir that temp operations are rooted in. But if I'm wrong thats good to know too :)  - and perhaps capture somehow

Comment (rbtcollins) [reply src/dist/temp.rs:161]: On the other other hand, this is clean() which suggests preservation of the dir - so ok, lets leave this as a future puzzle.

**Review by rbtcollins — APPROVED** [review]

File: src/dist/temp.rs (hunk 5 above)
Comment (rami3l) [reply src/dist/temp.rs:161]: > You added a regression test for that, so empirical validatation of whether its the one or not should be quite easy.

@rbtcollins Replacing this line with the old implementation gives:

```console
out.stderr (18 lines):
    info: syncing channel updates for 'nightly-aarch64-apple-darwin'
    info: latest update on 2015-01-02, rust version 1.3.0 (hash-nightly-2)
    info: downloading component 'cargo'
    info: downloading component 'rust-docs'
    info: downloading component 'rust-std'
    info: downloading component 'rustc'
    info: removing previous version of component 'cargo'
    info: removing previous version of component 'rust-docs'
    info: removing previous version of component 'rust-std'
    info: removing previous version of component 'rustc'
    info: installing component 'cargo'
    info: installing component 'rust-docs'
    info: installing component 'rust-std'
    info: installing component 'rustc'
    info: cleaning up downloads & tmp directories
    thread 'main' panicked at src/utils/utils.rs:616:13:
    Unable to clean up <snip>/rustupRd3iIp/tmp: Os { code: 62, kind: FilesystemLoop, message: "Too many levels of symbolic links" }
```

So I guess both pieces are indeed required for the fix to work.
