### PR TITLE
Use "true" for force_update in relevant install_from_dist calls in config.rs

### LINKED ISSUE #2068: builds fail due to missing components on non tier 1 platforms using the default profile
**Problem**
On platforms that don't have rustfmt and/or clippy, packages that use a rust-toolchain file that contains a toolchain that isn't already present on the host machine will fail because cargo does not call rustup with the --force option. e.g.

```
$ rustup toolchain install nightly-2019-10-02-powerpc64le-unknown-linux-gnu         
info: syncing channel updates for 'nightly-2019-10-02-powerpc64le-unknown-linux-gnu'
info: latest update on 2019-10-02, rust version 1.40.0-nightly (702b45e40 2019-10-01)
error: some components unavailable for download for channel nightly-2019-10-02: 'clippy', 'rustfmt'
If you require these components, please install and use the latest successful build version,
which you can find at <https://rust-lang.github.io/rustup-components-history>.

After determining the correct date, install it with a command such as:

    rustup toolchain install nightly-2018-12-27

Then you can use the toolchain with commands such as:

    cargo +nightly-2018-12-27 build
```
This is problematic for 2 reasons. 1, it probably shouldn't happen at all unless the package actually depends on one of those tools, and 2, nothing in the above message says anything about --force being a thing, so it's not obvious how I can fix it. I had to ask on discord to figure that out. 

```
$ rustup --version
rustup 1.20.2 (13979c968 2019-10-16)
```

### PR DESCRIPTION
**Pull request by BeniCheni**
> ... there're three sites which call `install_from_dist()` in the `config.rs::Cfg code`, and the one in `update_all_channels()` should be left alone. As such there are two sites to amend a boolean ...

> The difficulty will be in devising a nice set of tests to verify that this works ...

This PR resolves #2068 by updating the `force_update` param from ~`false`~ to `true` in relevant `install_from_dist()` calls in config.rs, and provides two tests to mimic the users cases where these `install_from_dist` calls would occur. (Could update the tests better under review guidance. Thanks in advance.)

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
The implementation is good; but are you certain that the tests fail if you don't have the src/config.rs change?

**Comment by BeniCheni** [comment]
@kinnison, I've done some local testing using latest `master` without src/config.rs change, and then using the current branch with the change.

Below seems to validate that ` rustup run --install nightly-2019-07-12 cargo -V` would fail in `master`, and would install the missing toolchain correctly in the PR branch.

Please let me know if there are other ways you'd like me to test to validate more. Thanks.

<details>
<summary>`master` version failed the download</summary>

```
# ~/github/rustup.rs on git:master
→ rustup -V                                       
rustup 1.20.2+20 (6dbf494bb 2019-10-19)

# ~/github/rustup.rs on git:master
→ rustup toolchain uninstall nightly-2019-07-12                    
info: no toolchain installed for 'nightly-2019-07-12-x86_64-apple-darwin'

# ~/github/rustup.rs on git:master
→ rustup run --install nightly-2019-07-12 cargo -V                           
info: syncing channel updates for 'nightly-2019-07-12-x86_64-apple-darwin'
info: latest update on 2019-07-12, rust version 1.38.0-nightly (4bb6b4a5e 2019-07-11)
error: component 'clippy' for target 'x86_64-apple-darwin' is unavailable for download for channel nightly-2019-07-12
```
</details>

<details>
<summary>PR version installed</summary>

- "warning: Force-skipping unavailable component 'clippy-x86_64-apple-darwin'" message seems to confirm the force flag being truthy to help the install

```
# ~/github/rustup.rs on git:install-from-dist-w-force-update-from-cfg
→ rustup -V                        
rustup 1.20.2+21 (50206cf6b 2019-10-19)

# ~/github/rustup.rs on git:install-from-dist-w-force-update-from-cfg
→ rustup toolchain remove nightly-2019-07-12 
info: no toolchain installed for 'nightly-2019-07-12-x86_64-apple-darwin'

# ~/github/rustup.rs on git:install-from-dist-w-force-update-from-cfg
→ rustup run --install nightly-2019-07-12 cargo -V
info: syncing channel updates for 'nightly-2019-07-12-x86_64-apple-darwin'
info: latest update on 2019-07-12, rust version 1.38.0-nightly (4bb6b4a5e 2019-07-11)
warning: Force-skipping unavailable component 'clippy-x86_64-apple-darwin'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
 11.7 MiB /  11.7 MiB (100 %)   7.8 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
168.8 MiB / 168.8 MiB (100 %)   7.3 MiB/s in 21s ETA:  0s
info: downloading component 'rustc'
 58.8 MiB /  58.8 MiB (100 %)   8.0 MiB/s in  7s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'rust-docs'
 11.7 MiB /  11.7 MiB (100 %)   2.2 MiB/s in  4s ETA:  0s
info: installing component 'rust-std'
168.8 MiB / 168.8 MiB (100 %)  14.2 MiB/s in 10s ETA:  0s
info: installing component 'rustc'
 58.8 MiB /  58.8 MiB (100 %)   7.6 MiB/s in  7s ETA:  0s
info: installing component 'rustfmt'
cargo 1.38.0-nightly (677a180f4 2019-07-08)
```
</details>

**Comment by kinnison** [comment]
Right, but do your test cases behave this way -- an easy way to check that is to simply temporarily change the trues back to falses and run those new tests -- if they fail with `false` but pass with `true` then that's good enough :D

**Comment by BeniCheni** [comment]
> an easy way to check that is to simply temporarily change the trues back to falses and run those new tests

@kinnison, you were right about that the previous tests were inefficient that there was no difference when reverting the booleans.

So I rewrote the test w. `make_component_unavailable` in test code to mimic an unavailable component of nightly, and then `rustup run --install nightly rustc --version` to confirm the force install.

I also confirmed that test would fail before the boolean change, and then with the boolean change the test passed as expected. PTAL?

</details>

<details>
<summary>Test failed before the boolean change in config.rs</summary>

```
→ cargo test run_with_install_flag_against_unavailable_component
   Compiling rustup v1.20.2 (/Users/bchen/github/rustup.rs)
    Finished dev [unoptimized + debuginfo] target(s) in 23.97s
     Running target/debug/deps/rustup-b6ab2206befdfe0d
...
running 1 test
test run_with_install_flag_against_unavailable_component ... FAILED

failures:

---- run_with_install_flag_against_unavailable_component stdout ----
Copying from /Users/bchen/github/rustup.rs/target/debug/rustup-init to /Users/bchen/github/rustup.rs/target/tests/running-test-9U9ht7/rustup-exeScqntI/rustup
running "/Users/bchen/github/rustup.rs/target/tests/running-test-9U9ht7/rustup-exeScqntI/rustup" "set" "default-host" "x86_64-apple-darwin"
status: exit code: 0
----- stdout

----- stderr

/Users/bchen/github/rustup.rs/target/tests/running-test-9U9ht7/rustup-distr3PtDU/dist/channel-rust-nightly.toml.sha256
running "/Users/bchen/github/rustup.rs/target/tests/running-test-9U9ht7/rustup-exeScqntI/rustup" "run" "--install" "nightly" "rustc" "--version"
status: exit code: 1
----- stdout

----- stderr
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2015-01-02, rust version 1.3.0 (hash-nightly-2)
info: skipping nightly which is missing installed component 'rust-std'
info: syncing channel updates for 'nightly-2015-01-01-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-31-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-30-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-29-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-28-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-27-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-26-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-25-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-24-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-23-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-22-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-21-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2014-12-20-x86_64-apple-darwin'
error: component 'rust-std' for target 'x86_64-apple-darwin' is unavailable for download for channel nightly


> rustup run --install nightly rustc --version
out.ok: false
out.stdout (0 lines):
    
out.stderr (17 lines):
    info: syncing channel updates for 'nightly-x86_64-apple-darwin'
    info: latest update on 2015-01-02, rust version 1.3.0 (hash-nightly-2)
    info: skipping nightly which is missing installed component 'rust-std'
    info: syncing channel updates for 'nightly-2015-01-01-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-31-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-30-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-29-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-28-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-27-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-26-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-25-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-24-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-23-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-22-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-21-x86_64-apple-darwin'
    info: syncing channel updates for 'nightly-2014-12-20-x86_64-apple-darwin'
    error: component 'rust-std' for target 'x86_64-apple-darwin' is unavailable for download for channel nightly
    
expected.ok: true
expected.stdout (1 lines):
    1.3.0 (hash-nightly-2)
    
expected.stderr (9 lines):
    info: syncing channel updates for 'nightly-x86_64-apple-darwin'
    info: latest update on 2015-01-02, rust version 1.3.0 (hash-nightly-2)
    warning: Force-skipping unavailable component 'rust-std-x86_64-apple-darwin'
    info: downloading component 'cargo'
    info: downloading component 'rust-docs'
    info: downloading component 'rustc'
    info: installing component 'cargo'
    info: installing component 'rust-docs'
    info: installing component 'rustc'
    
[tests/mock/clitools.rs:257] out.stdout == stdout = false
[tests/mock/clitools.rs:258] out.stderr == stderr = false
thread 'run_with_install_flag_against_unavailable_component' panicked at 'explicit panic', tests/mock/clitools.rs:259:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    run_with_install_flag_against_unavailable_component

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 67 filtered out

error: test failed, to rerun pass '--test cli-v2'
```
</details>

<details>
<summary>Test passed after the boolean change in config.rs</summary>

```
→ cargo test run_with_install_flag_against_unavailable_component
   Compiling rustup v1.20.2 (/Users/bchen/github/rustup.rs)
    Finished dev [unoptimized + debuginfo] target(s) in 18.51s
     Running target/debug/deps/rustup-b6ab2206befdfe0d
...
running 1 test
test run_with_install_flag_against_unavailable_component ... ok
```
</details>

File: tests/cli-v2.rs [hunk 1]
```diff
@@ -1185,3 +1185,36 @@ fn test_complete_profile_skips_missing_when_forced() {
...
+                "nightly",
+                "rustc",
+                "--version",
+            ],
+            "1.3.0 (hash-nightly-2)
+",
+            for_host!(
+                r"info: syncing channel updates for 'nightly-{0}'
+info: latest update on 2015-01-02, rust version 1.3.0 (hash-nightly-2)
+warning: Force-skipping unavailable component 'rust-std-x86_64-apple-darwin'
```
Comment (kinnison) [inline tests/cli-v2.rs]: Unfortunately I imagine this will also cause problems.  You need:
```suggestion
warning: Force-skipping unavailable component 'rust-std-{0}'
```
most likely

**Review by kinnison — CHANGES_REQUESTED** [review]
If you can fix the test case, I think this looks good.  Nice job.

**Comment by kinnison** [comment]
Since I had some time, I made the change for you and pushed a commit.  if you're okay with it, and it passes tests, then please fold it into your commit appropriately and then we'll be good to merge.

**Comment by BeniCheni** [comment]
> ... if you're okay with it, and it passes tests, then please fold it into your commit appropriately and then we'll be good to merge.

@kinnison, ah my bad. Didn't use wildcard w. `nightly-{0}` in one of the expected message line, as your push fixed it up. 🙏 I've passed all the tests locally and folded into a single commit in last push. PTAL?

P.S.: Thanks for your comment that led to the learning about `make_component_unavailable` fn in test code interesting and helpful, in case a future PR would need to write tests w. unavailable components.

**Review by kinnison — APPROVED** [review]
LGTM
